### ISSUE TITLE
Integration with other storages services

### ISSUE THREAD

**Issue by rickbenetti** [buttercup/buttercup-mobile#102]
It's possible to add new services like pCloud support?

Today I needed has dropbox account open to use only for buttercup.

**Comment by perry-mitchell** [comment]
Hi @rickbenetti - [Most cloud hosting services actually support WebDAV](https://community.cryptomator.org/t/webdav-urls-of-common-cloud-storage-services/75) out of the box, which Buttercup supports. You can use this to connect each of our apps to your account.

**Comment by perry-mitchell** [comment]
I'll close this issue, as WebDAV should be supported for pCloud. Other integrations can be discussed in the roadmap.
