### ISSUE TITLE
Can't open file on Windows and iOS app closes when try to open same file

### ISSUE THREAD

**Issue by mcid86** [buttercup/buttercup-mobile#110]
Hi, I'll try to explain my issue:

When I try to open a file on a PC i get the next message: "Error: authentication failed". When I try to open the same file on an iphone then the app closes after entering the master code. I don't have any way of opening that file.

My PC has Win 10 OS and I have an iphone 6 with iOS 11.4.1.

Steps on iphone:
1) Add
2) Choose Dropbox
3) I authenticate
4) Connect
5) Choose the file
6) Enter master key
7) Enter archive name
8) The file is added and when I try to access to it, I enter the password, I get "Unlocking" message  and then the app closes.

Steps on PC:
1) File - Open archive - Chose the file
2) Enter the password and get "Error: Authentication failed." message

The file was created on PC with an older version of Buttercup. I tried to open he file with an older version of the software but i got the same issue. I also tried creating a new file and I was able to open it without any trouble even on PC and iphone.
I hope you could help me, is very important for me. Thanks in advance.

Matías Cid

**Comment by perry-mitchell** [comment]
Hi - First of all sorry for the issue. We wouldn’t expect there to be any issue here, as we have tests checking all older vault versions to ensure that they can still be opened in today’s versions.

You could try to download and open an older version of the desktop application from the releases section on github. If you open an [older version](https://github.com/buttercup/buttercup-desktop/releases?after=v1.4.0) perhaps that helps? Not sure what could have gone wrong here however..

**Comment by mcid86** [comment]
Hi Perry, thank you very much for your quick response. I tried open the vault with two different old versions but unluckily y had the same problem. Is there any other option for opening the file? I have many passwords on that file, it would be really important to me opening it. Thanks in advance. 

Matías

**Comment by perry-mitchell** [comment]
Hmm.. Currently it sounds like either your archive is corrupt, or your password is wrong. If either of these are the case, there's nothing that we can do to help unfortunately.

You should start by identifying the version of Buttercup used to create the archive, and try to remember if the password is correct. You could install that exact version of the desktop app to open it. If this doesn't work, I'm afraid the file is most likely corrupt. You should, in my opinion, endeavour to use a file storage host like Dropbox or ownCloud, where **file versioning** is available. This can help back up changes and prevent irreversible corruption.

**Comment by mcid86** [comment]
Hi Perry, unluckily I can't remember the exactly version of Buttercup used to create the archive. I tried several old versions but none of the worked. I'm completely sure that the password I'm using is the correct one, so I asume that the file must be corrupted. I'll have to take the hard job of recovering all the passwords from all the sites. 
I'll take into account using a file storage like Dropbox, thanks for the advise and thank you very much for your help.

Matías

**Comment by perry-mitchell** [comment]
Hi @mcid86, did you have any update on this? 

On another note, we'll hopefully soon have backup implemented so previous copies of your vault will be safe. We're sorry you had such an issue.

**Comment by mcid86** [comment]
Hi Perry, unluckily I couldn't find a way to open the vault. I'm in the process of recovering all the passwords and then create a new vault. Thank you for your help. I'll close this issue.
