### ISSUE TITLE
V1.5.0 Does not authenticate in Dropbox

### ISSUE THREAD

**Issue by regoremor** [buttercup/buttercup-mobile#117]
I have downloaded I have installed the latest version and now I can not authenticate in Dropbox.

**Comment by perry-mitchell** [comment]
Hi,

I just did some quick tests and I can’t reproduce any issue with Dropbox. What model phone and OS are you using?

Are you able to log on to the Dropbox website on your phone?

Can you describe the problem in more detail?

Thanks

**Comment by regoremor** [comment]
Thank you very much for the answer. Apparently it was Dropbox issue or the network I was connected, because now I can authenticate.
