### ISSUE TITLE
Seafile webdav failing on both iOS and Android

### ISSUE THREAD

**Issue by imkwx** [buttercup/buttercup-mobile#123]
Hi !

Now that we got seafile working for the desktop and browser app, I've tried it on mobile.
Here's the problem : On both iOS and Android it seems that it's not working.
Everytime I try to add an archive via WebDAV I get a Connection Error (see screenshot attached)

![screenshot_20181018-115553_buttercup](https://user-images.githubusercontent.com/19341212/47147090-be70eb00-d2cd-11e8-9cac-f049c68cd3bc.jpg)

```
Error: Connection failed
undefined is not an object (evaluating 'p("response",o).filter')
```

I did not try with another webdav source, so I don't know if it affects only seafile's webdav or any webdav.

Have a good day!

**Comment by perry-mitchell** [comment]
Hi @imkwx - We have not yet released the fix for mobile. Our release schedule there is much slower, so I would expect something to go out next week.. hopefully.

Cheers!

**Comment by perry-mitchell** [comment]
Hi @imkwx - Any chance to test this again on iOS? We've released a fix for it.

The android version is still not released due to issues there - #129

**Comment by imkwx** [comment]
Hi @perry-mitchell,

I confirm that both iOS and Android version are working perfectly 👌 

Thanks a lot :D

**Comment by perry-mitchell** [comment]
Amazing @imkwx - Thanks so much for the help and patience.
