### ISSUE TITLE
To be able to open an archive with Google Drive.

### ISSUE THREAD

**Issue by franco27** [buttercup/buttercup-mobile#143]
I would like to be able to open an archive with Google Drive. 

I would like you to add this feature.  I'm on Android.

Currently I am blocked because I can't open an archive locally from my smartphone.  For me your application is unusable.

**Comment by perry-mitchell** [comment]
We have an issue for this in the core: buttercup/buttercup-core#187

I see no need for separate issues in each app's repo, as all apps will get the support if it's added in the core.
