### ISSUE TITLE
unable to delete archive on mobile app

### ISSUE THREAD

**Issue by vkuznet** [buttercup/buttercup-mobile#144]
Hi,
I just installed buttercup mobile app and was playing with different cloud providers. I created one on webDav provider now I can't delete it. In fact, I can't find any option on mobile app to delete existing archive. Could you please add such option.
Thanks,
Valentin.

**Comment by perry-mitchell** [comment]
Hi!

You also can't delete vaults on the desktop application when using cloud services. To be honest I'm not sure if we _really_ need this functionality as you could just as easily delete the file from the interface you use to browse the cloud service. It could be argued that Buttercup shouldn't concern itself with too much of the file management aspect of connecting to cloud services.

That, and this would add more complexity to the application which would need to be maintained. Deleting and waiting for files to be deleted. For that reason I'll close this issue for now. Thank you!

**Comment by vkuznet** [comment]
Well, you probably mis-understood the request. Yes, I can delete the file on cloud provider. But the archive remains visible in mobile app pointing to non-existing file. And, if I click on it I get error that archive is failed to be open with suggestion to try to open it in offline mode. I considered it as a bug in web UI interface in mobile app.

**Comment by vkuznet** [comment]
so my only option so far is to reinstall mobile app since there is no way I can remove archive which points to non-existing file.

**Comment by perry-mitchell** [comment]
Oh, I see.. I'm sorry I did misunderstand. Have you tried swiping the vault to the left? It reveals a delete button for removing the vault from the UI.

**Comment by vkuznet** [comment]
Ahh, silly me, yes it works, sorry for the noise, but good to know that you take care of your customers.

**Comment by perry-mitchell** [comment]
@vkuznet No worries! Our usage docs are lacking which may have helped here. Thanks for seeing it through with us!
