### ISSUE TITLE
Default android icons in application.

### ISSUE THREAD

**Issue by dutchtux3000** [buttercup/buttercup-mobile#145]
In the Android version 1.7.0 that is in the playstore It still has the default android icons and is shown to me on my device.
After looking in the source-code I found the following files still has the default icon:
- \android\app\src\main\res\mipmap-hdpi\ic_launcher_round.png
- \android\app\src\main\res\mipmap-mdpi\ic_launcher_round.png
- \android\app\src\main\res\mipmap-xhdpi\ic_launcher_round.png
- \android\app\src\main\res\mipmap-xxhdpi\ic_launcher_round.png
- \android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png
- \android\app\src\main\res\mipmap-xxxhdpi\ic_launcher_round.png

My device seems to use the file: \android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png

Here are specs of my device:
**Device:** OnePlus 5T 
**OS:** Android
**Version:** 9.0 (Pie)

**Comment by pleswi** [comment]
FYI: https://android-developers.googleblog.com/2019/03/introducing-new-google-play-app-and.html

**Comment by nisrulz** [comment]
Hi @perry-mitchell I would like to help here 😺 

Let me know if I should look into this.
