### ISSUE TITLE
Google Drive support

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#148]
Integrate Google Drive in the mobile app.

**Comment by ApolllonDev** [comment]
Hi, @perry-mitchell,
I would like to work on this issue.
This is my first time contributing to the project and I would really appreciate some guidance with this feature implementation.

**Comment by perry-mitchell** [comment]
@ApolllonDev That’d be great! We’d be happy to help. My recommendation is to start with a PR that we can help you with. Google drive is complex enough that we should expect some challenges, but it essentially works the same as Dropbox.

Let us know if you get started!

**Comment by ApolllonDev** [comment]
@perry-mitchell It seems that Dropbox has an [icon](https://github.com/buttercup/buttercup-mobile/blob/master/resources/images/dropbox-256.png) in the `resources/images/` folder.
Unfortunately, there isn't one for Google Drive and the project is under GNU v3.0 License which includes `Commercial use` and `Modification`. Thus, there isn't a `256x256` icon available for commersial reuse with modification when I am performing a Google search. Please advise.

**Comment by ApolllonDev** [comment]
I checked the Dropbox files with `t` search and it seems that I have to add some new stuff and do some modifications as well. I am planning to create the following files:
- [ ] source/actions/googleDrive.js
- [ ] source/library/googleDrive.js
- [ ] source/selectors/googleDrive.js
- [ ] resources/images/googleDrive-256.png (follow up with this one)
- [ ] source/reducers/googleDrive.js 
- [ ] source/components/GoogleDriveAuthButton.js
- [ ] source/containers/GoogleDriveAuthButton.js

Additionally, following files will be modified:
- [ ] source/actions/types.js
- [ ] package.json

I am planning to use this [npm package](https://www.npmjs.com/package/googledrive).
It has `client.json` file as an [authentication requirement](https://github.com/rndomhack/node-googledrive/issues/1#issuecomment-375947628).

**Comment by perry-mitchell** [comment]
Hi @ApolllonDev - Thanks for touching base. Apologies for not coming back sooner.

> Unfortunately, there isn't one for Google Drive and the project is under GNU v3.0 License which includes Commercial use and Modification

In my opinion this is fine - Buttercup mobile isn't "commercial use" as it's free and open source. Even if we add our paid option in there later, it won't have anything to do with Google or Google Drive, so I don't think there's any conflict there. We're already using the icon in the browser extension, and we've had that **reviewed by Google personnel** already.

> I am planning to create the following files

Looks good!

> I am planning to use this npm package.
> It has client.json file as an authentication requirement.

Sounds good too. We used a simple OAuth redirect in the extension, but we're still seeing issues with the OAuth token and refreshing it. I'd be interested to see how it goes here. Do you plan to perform all of the OAuth stuff using that package?

**Comment by perry-mitchell** [comment]
Actually @ApolllonDev, we'd probably prefer it if you used [our client for Google Drive access](https://github.com/buttercup/googledrive-client). Would be nice to keep it consistent across the platforms. Also, ours simply uses REST and doesn't require the googleapis project.

**Comment by ApolllonDev** [comment]
@perry-mitchell I will look into that, thank you for your suggestion 👍

**Comment by ApolllonDev** [comment]
#151

**Comment by perry-mitchell** [comment]
Quick update: After toiling with react-native-app-auth, it seems it doesn't support app extensions, which Buttercup relies on for mobile browser form autofill. Due to this, we're forced to use something else to get google signin working. Something like this: https://github.com/react-native-community/react-native-google-signin

Work is underway and should be completed in the very near future.
