### ISSUE TITLE
[Dropbox] Can't open archive on Samsung S6 Edge

### ISSUE THREAD

**Issue by liloumuloup** [buttercup/buttercup-mobile#149]
Hello,

I have some troubles with my archive. 

I had to switch from my Huawei P9 lite to a Samsung S6 Edge and i can't open my archive hosted on Dropbox.

I can still open it on my computer so it is not corrupted.

Here is a screenshot of the error. 

![Error:Failed unlocking archive](https://i.imgur.com/ELpJzBf.png) 

As you can see, i have network access and the other apps work perfectly. 

Is there anything i can do to solve this ? 

Best regards.

**Comment by liloumuloup** [comment]
After browsing some issues, here is a piece of information to help :
* Samsung Galaxy S6 Edge SM-G925F
* Android 7.0

How to reproduce this issue :
* Add archive
* Choose Dropbox as source
* Authenticate to your Dropbox account
* Connect to find your Buttercup archive in your Dropbox
* Type your password when asked
* Wait and see the error

Let me know if there is something missing. :relaxed:

Best regards.

**Comment by frederic-klein** [comment]
Same here: Huawei P9 Lite, Android 7.0, Dropbox, same error.
No problem on other devices and worked for a while.

**Comment by Shmii** [comment]
Same error here : My phone is a "Leagoo S8" with Android7
No problem on other devices and worked for a while.

**Comment by ThisInsider** [comment]
Same here on my Samsung Galaxy S6 Edge+

**Comment by ThisInsider** [comment]
@perry-mitchell can this issue at least get a priority tag? App not working on all devices is a pretty big deal..

**Comment by perry-mitchell** [comment]
I think this is to do with the Android version - As you've seen, less than Android 8 was deprecated some time ago. This is to match the guidelines and *restrictions* put in place my Google and their Play Store.

**Comment by perry-mitchell** [comment]
Apologies for taking so long to see this - I'm sorry you all have had to wait for an answer. But unfortunately there's nothing we can do, realistically, to support older android versions. Android 8 isn't even the latest major version anymore, so I'd expect there to be little reason to not upgrade (besides carrier restrictions of course).

I'll close this as nothing to do.
