### ISSUE TITLE
Improve label on button to hide/display info

### ISSUE THREAD

**Issue by pedrolucasp** [buttercup/buttercup-mobile#152]
When seeing a entry on a Archive, all sensitive data is blurred. To display, one must click the  __view hidden__ button, which is a weird label for it. I suggest to change to something along the lines of:
_Display sensitive information_
_Hide sensitive information_

References:
![no-info](https://user-images.githubusercontent.com/861658/56237534-98e95200-6062-11e9-8500-b88449f00e7a.jpeg)

![with-info](https://user-images.githubusercontent.com/861658/56237536-9a1a7f00-6062-11e9-80c0-02e7867eb31e.jpeg)

**Comment by perry-mitchell** [comment]
Sounds good! It's a 👍 from me.
