### ISSUE TITLE
Question: How to translate the GUI to other languages?

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-mobile#154]
My father is using Buttercup on iOS, but he does not speak English. That's why I would like to translate the GUI to German. The only locale I found is for the desktop client:
https://github.com/buttercup/buttercup-desktop/blob/master/locales/en/base.json

But how can I translate the GUI of the iOS and Android App to German?

**Comment by perry-mitchell** [comment]
@julianpoemp That's really cool! As you've noticed we don't yet have localisation on mobile, but I imagine we'd want to use much the same system as with the desktop client - see #70.

I'll close in favour of that :)
