### ISSUE TITLE
Crash on most devices with last version

### ISSUE THREAD

**Issue by eldy** [buttercup/buttercup-mobile#158]
Version: 22 avril
Since the last version, buttercup is not able to launch on any device.
I can't access buttercup anymore on LG4. It crashes too just after launching it.
I installer it on a Nexus 5, it crashes too just after launching it.
Tested on a Wiki, it crashes too just after launching it.
All those phones were ok with previous version.

i sent several crach report from google play system.
One of this issue is called "Crash issue #158"

**Comment by perry-mitchell** [comment]
Seems to be that our most common problem is nicely listed in our play console:

![image](https://user-images.githubusercontent.com/3869469/57863985-c06b4000-7803-11e9-9d69-5bacd3df3195.png)

![image](https://user-images.githubusercontent.com/3869469/57864061-e690e000-7803-11e9-813c-4fa49f7c1141.png)

The error is a simple one thankfully.. perhaps state updates are slow and an unknown archive type error is being thrown. We've patched this and will be releasing shortly.

**Comment by perry-mitchell** [comment]
Released 1.8.2 which should hopefully fix this.

**Comment by HVK500** [comment]
Unfortunately it does not fix the issue. It seems the autofill is not playing nice. 

com.facebook.react.common.JavascriptException: Java exception in 'NativeModules'

java.lang.NoClassDefFoundError: android.service.autofill.Dataset$Builder, stack:
libcore.reflect.InternalNames.getClass@55
java.lang.Class.getDexCacheType@476
java.lang.reflect.AbstractMethod.getParameterTypes@166
java.lang.reflect.Method.getParameterTypes@170
java.lang.Class.getDeclaredMethods@673
com.facebook.react.bridge.JavaModuleWrapper.findMethods@88
com.facebook.react.bridge.JavaModuleWrapper.getMethodDescriptors@118
android.os.Handler.handleCallback@815
android.os.Handler.dispatchMessage@104
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@29
<unknown>@774:1669
v@2:1489
d@2:949
o@2:435
<unknown>@773:646
v@2:1489
d@2:949
o@2:435
<unknown>@771:1243
v@2:1489
d@2:949
o@2:435
<unknown>@768:1107
v@2:1489
d@2:949
o@2:435
<unknown>@731:1140
v@2:1489
d@2:949
o@2:435
<unknown>@730:1301
v@2:1489
d@2:949
o@2:435
<unknown>@723:1909
v@2:1489
d@2:949
o@2:435
<unknown>@490:466
v@2:1489
d@2:949
o@2:435
<unknown>@489:203
v@2:1489
d@2:949
o@2:435
<unknown>@488:194
v@2:1489
d@2:949
o@2:435
<unknown>@483:284
v@2:1489
d@2:949
o@2:435
<unknown>@408:2028
v@2:1489
d@2:949
o@2:435
<unknown>@403:295
v@2:1489
d@2:949
o@2:435
<unknown>@401:215
v@2:1489
d@2:949
o@2:435
<unknown>@310:278
v@2:1489
d@2:949
o@2:435
<unknown>@12:191
v@2:1489
d@2:879
o@2:435
global code@973:4

	at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:207)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:818)

**Comment by perry-mitchell** [comment]
@eldy What version of Android are you running? I don't recognise the avril specification you mentioned.

@HVK500 Same question - What version of android?

You must be running at least android 8.0 to use the latter versions of the app.

**Comment by Neogrey** [comment]
I'm using Android 6 on Nexus 5 and as well cannot open buttercup without crash.

@perry-mitchell would be possible to release a legacy version for Android 6 ?.

**Comment by HVK500** [comment]
@petty-mitchell I'm using version 6

**Comment by perry-mitchell** [comment]
Ok, well that will be the reason then.

We support only Android 8 and newer - earlier versions are not supported and will almost certainly crash due to lack of necessary libraries. We've released in this manner due to guidelines set out by Google themselves, deprecating all older Android versions and forcing Play store publishers (like ourselves) to only release 8 or never - it's not possible to release for older OSes in the play store. That, and you should be updating regardless for security purposes at very least.

I'm sorry for the inconvenience, but I hope that you'll consider to upgrade your OS where you're able. I'll close this as there's nothing we can do in terms of development effort.
