### ISSUE TITLE
Detect touch/face ID disabled: Use password mode instead

### ISSUE THREAD

**Issue by saman** [buttercup/buttercup-mobile#160]
** Describe the issue you're having **

I have added the Touch ID unlock feature. It was perfectly working until the Touch ID got broken. I have disabled Touch ID totally in the phone settings, but Buttercup is not even allowing me to unlock with the master password. It only shows an error "Device does not support Touch ID".

** What OS version are you using **

iOS 12.3.1

** What device are you using **

iPhone SE

** Screenshot **
![IMG_6699](https://user-images.githubusercontent.com/1576246/59289510-86f8e980-8c76-11e9-9925-64432d507f17.PNG)

**Comment by perry-mitchell** [comment]
This is indeed an issue - in the mean time you can delete the vault in the app and add it again - it should not prompt for touch after that.

**Comment by perry-mitchell** [comment]
@saman Taking another look at this, was touch unlock still disabled in settings when trying this? If so then I'm not sure that this is something that ultimately needs fixing.. Disabling touch unlock when vaults are set to require it is probably a very uncommon use case..

**Comment by saman** [comment]
The point is my Touch ID suddenly stopped working. I couldn't find any Enable radio to stop Touch ID completely in iOS settings, I had to remove all fingerprints to disable it completely. 
Also, I disabled the all other option of it.

As I checked the other apps, they just asked for the password. I think in this case if there is no Touch ID, Buttercup can asks for the vaults' master password.

**Comment by perry-mitchell** [comment]
As I'm not sure I completely understand how this issue can come about (how touch unlock can stop working), I'll simply mark this as a task to detect if touch/face unlock is not available.

**Comment by teon** [comment]
Also, when "my face" is not recognized - normally applications ask for a passcode, but here I just get this error message and can't access my vault (cant input passcode or the valt password).

**Comment by prestopasto** [comment]
I debated on opening a separate issue for this, but I think this is related...  I've had instances where biometrics (fingerprint) was enabled on a vault and have not been unable to unlock it.  For example, after swimming my fingers are wrinkly and I can't unlock any vaults for 30-45 minutes until my fingers return to close to normal shape.  It would be great if there was a option to switch to the passcode input or if it would fallback to the passcode input after so many failed attempts at using the biometric unlock.

**Comment by perry-mitchell** [comment]
Happy to accept a PR for this, don't have time myself to look at it yet.

**Comment by perry-mitchell** [comment]
This should be automatic in v2.
