### ISSUE TITLE
NextCloud fails on Android, network error

### ISSUE THREAD

**Issue by joelrader** [buttercup/buttercup-mobile#161]
Network error to NextCloud

Trying to add a database to my Android app on first run of the app. Using my NextCloud instance as a target. Credentials work for my NextCloud app on same phone.

Android 9 on a Moto X4

My URL is in the form of:
https://files.mydomain.com:12345

Currently I'm using a self-signed cert, so maybe Buttercup expects no cert errors? I'm due to swap in a Let's Encrypt cert soon.

I can create a account for you if you'd like to test as well.

**Comment by perry-mitchell** [comment]
Hi! Yes unfortunately self-signed certificates won't work. Buttercup strongly follows how browsers work, as it usually uses browser-side clients to make requests. In that way, it's restricted by certificate rules that browsers impose without modifying their settings - so self-signed certificates are actually invalid. A lets-encrypt cert should work as it's verifiable by browsers.

**Comment by hobleyd** [comment]
I can confirm that a LetsEncrypt certificate does indeed work.

**Comment by perry-mitchell** [comment]
I'll close this as it's most likely to do with self-signed certificates, which Buttercup does not support. Lets Encrypt is the way to go for free certs.

**Comment by David-Lor** [comment]
Hello there! I guess there's nothing new about this issue, right? In my case I'm using a self-hosted Nextcloud instance that is not exposed to the Internet, so Let's Encrypt does not work in this case.

Probably #265 could be an alternative.

**Comment by hobleyd** [comment]
If you have a domain name, you can use DNS records to allow LetsEncrypt to issue an SSL cert which can then be imported to nextcloud. Even if your nextcloud instance is not publicly available.

**Comment by David-Lor** [comment]
@hobleyd Yeah, I though about that, requesting a LetsEncrypt cert for a public domain, which in LAN, with a local DNS server, resolves to my server... I may try it.
