### ISSUE TITLE
app doesn't start properly on Xiaomi Mi Pad 4.

### ISSUE THREAD

**Issue by hobleyd** [buttercup/buttercup-mobile#166]
When I run the app on my Xiaomi MiPad 4 tablet, it starts with the "Allow display over other apps" setting page displayed; but tapping on the back icon simply redisplays the same page over and over. There appears to be no way to get into the app sadly.

It happens everytime when starting the app.

Android 8.1.0, patch level 2019-01-01.

Cheers,
David

**Comment by perry-mitchell** [comment]
Do you "Allow display over other apps"? It's required for Buttercup to work.

**Comment by hobleyd** [comment]
In the System Settings it says that it has Draw over other Apps. When I run the app, it brings up that settings screen with the option defaulted to true.

When I click the back button to exit that screen it simply redisplays the screen. The same happens if I unclick the setting and reclick it again.

**Comment by hobleyd** [comment]
In the System Settings it says that it has Draw over other Apps. When I run the app, it brings up that settings screen with the option defaulted to true.

When I click the back button to exit that screen it simply redisplays the screen. The same happens if I unclick the setting and reclick it again.

**Comment by PierreBresson** [comment]
I have the same issue, I get "Allow display over other apps" and then after saying yes the app crash.
Galaxy S6 with Android 7.0
App version : 1.8.2

**Comment by hobleyd** [comment]
I think the problem is that it doesn't recognise the default option correctly the first time through. I set the Draw Over Other Apps to false; tried to exit and had it bring back the same screen. Then I force quite the app and started it again; this time when it brought up the Draw Over Other Apps setting screen, it was off and when I set it to true, everything started working.

**Comment by perry-mitchell** [comment]
@hobleyd That's really good news! To be honest I really dislike that permission screen, it's *not at all obvious* that it's required for the app. It should be a single dialog/popup. But good you got it solved! I'll close this for now.
