### ISSUE TITLE
dark mode

### ISSUE THREAD

**Issue by jean-io** [buttercup/buttercup-mobile#167]
Hi,

[iOS 13](https://www.apple.com/ios/ios-13-preview/) beta is out for developers and it brings dark mode to iPhones. 

1. Can Buttercup app get a dark mode too?
2. Can it be automatically turn on and off depending on system wide dark mode?

If it could be done, it would be great :heart_eyes:

Thank

**Comment by perry-mitchell** [comment]
Sounds great!

**Comment by julianpoemp** [comment]
this feature would be nice on Android, too 😄 👍

**Comment by perry-mitchell** [comment]
Available in v2.
