### ISSUE TITLE
Why `secrets.json` isn't included in the repo?

### ISSUE THREAD

**Issue by devgianlu** [buttercup/buttercup-mobile#173]
While building, an error popups saying `secrets.json` is missing, but there's nothing really secret inside it (client id + redirect URL). I think it should be included inside the repository since these information are accessible anyway if someone decompiles/unpacks the application.

This also regards the other "clients".

**Comment by perry-mitchell** [comment]
Hi @devgianlu - You raise a good question, and you're right that it's simple enough to unpack (I don't appreciate you sharing it here, but too late now).. I'd prefer to not have to share it as it is sensitive data and allows others to masquerade as our app.

We're not completely sure we want to commit it yet and would prefer to research a little more on what other extensions/apps are doing with regards to the same details.

**Comment by devgianlu** [comment]
Sorry for that, I just wanted to prove a point. If you don't want to publish the "production" credentials, I'd publish some placeholder credentials that let people pull and run the repository as is. No one will probably bother creating its own credentials just to try out the latest features.

I've seen this being done already, FastHub, for example, does this.

**Comment by perry-mitchell** [comment]
@devgianlu Not to be too pedantic, but I can see that fasthub ignore their secrets file, at least currently:

https://github.com/k0shk0sh/FastHub/blob/f40109e7f84dcc1d30d86563b698e1642e48b1b4/app/.gitignore#L2

**Comment by devgianlu** [comment]
Quite strange because I once compiled the [v5 branch](https://github.com/k0shk0sh/FastHub/tree/v5) and it logged me in with as "Demo FastHub". 

![image](https://user-images.githubusercontent.com/14827249/64374223-a3ad7f00-d023-11e9-9d58-5bdf748922f3.png)

**Comment by perry-mitchell** [comment]
Now included.
