### ISSUE TITLE
Another app for opening .bcup

### ISSUE THREAD

**Issue by mahdiKarami98** [buttercup/buttercup-mobile#174]
Hi. I have galaxy ground plus prime with android 6 and buttercup android app not start in my phone. And I understand buttercup android app need android 8.
Now what should I do now to access my password saved in my dropbox account as a .bucp file? Any app like buttercup can use my password saved in my dropbox account?

**Comment by perry-mitchell** [comment]
We have a [desktop app](https://github.com/buttercup/buttercup-desktop) and [browser extension](https://github.com/buttercup/buttercup-browser-extension) that can both read that file. I'm sorry for the inconvenience.. Good luck!
