### ISSUE TITLE
 v1.9.1-1.10.0 crashing on Android

### ISSUE THREAD

**Issue by pleswi** [buttercup/buttercup-mobile#180]
After morning update to 1.9.1 every try of start app immidietly ends with crash.

Android 9 with August security patches on Google Pixel 1

**Comment by liloumuloup** [comment]
Same here with Pocophone P1 from Xiaomi.  ![Screenshot Android version Xiaomi Pocophone P1](https://i.imgur.com/cdnNcWJ.png)

**Comment by divyanshu013** [comment]
Any way to rollback or get an older release? Unable to use passwords on mobile at the moment.

**Comment by perry-mitchell** [comment]
Hmm, would any of you happen to _not_ have Google Play services installed? Wondering if it's the google drive integration that's causing the issue.

**Comment by liloumuloup** [comment]
Well, i have Google Play installed and up to date.

I found a crash report in my phone. Here is the error i have, if it can help :
java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so
	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:703)
	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:564)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:500)
	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)
	at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)
	at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)
	at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:914)
	at java.lang.Thread.run(Thread.java:764)

**Comment by zappy16GB** [comment]
I have the same issue it keeps chrashing.
My device is a Google pixel 2 XL it happened after the update.

Everything is up to date
Please fix it fast I can't access passwords on mobile at this time.

**Comment by msilvestroni** [comment]
Same here! It seems a React Native issue. [[ANDROID] SoLoader error using App Bundle #23764](https://github.com/facebook/react-native/issues/23764)

**Comment by divyanshu013** [comment]
@perry-mitchell would it be possible to get the older version for the interim?

**Comment by julianpoemp** [comment]
same here!

Video: https://youtu.be/b20w6eZMpVk

System Info:
![Screenshot_20190908_180107_com android settings](https://user-images.githubusercontent.com/25926588/64490993-1b1d2180-d263-11e9-90e7-a2c900574b2c.jpg)

**Comment by liloumuloup** [comment]
Hello,

Little update : i tried to uninstall and reinstall the app but i still have the issue.

Thank you for your work.

Kind regards.

**Comment by ttamminen** [comment]
I have the same problem on OnePlus 3T on Buttercup version 1.9.1

The app crashes immediately, I have sent system log files on the crash. Hopefully, those are useful.

OxygenOS 9.0.5, Android version 9

**Comment by ckadluba** [comment]
I have the problem too on my Google Pixel 2 with Android 10. This bug seems critical because it makes buttercup unusable on Android.

**Comment by perry-mitchell** [comment]
I’m not familiar with how android updates work. Can you have multiple versions in the play store?

I can at least release the old APK here. I’ll be releasing a new version tomorrow and will upload the apk to the releases section too.

**Comment by se1exin** [comment]
@perry-mitchell roll the code back to the older version, and then just bump the `versionCode` and `versionName` in the app gradle file. Upload to Play as a new version and users will 'update' to the working state.

Not ideal but is the easiest way to distribute the fix/rollback.

**Comment by perry-mitchell** [comment]
Thanks @se1exin.

I just released 1.10.0, with the new RN version and fixes. Please try this - if this fails as astronomically as 1.9.1, I'll roll it back.

**Comment by pleswi** [comment]
App still crash. But autofill in chrome works partly.

**Comment by tasos-ale** [comment]
I am on release 1.10.0. Now it crashes with different error.
![viber_image_2019-09-14_12-21-32](https://user-images.githubusercontent.com/3420211/64906086-3ddb8a00-d6ea-11e9-86ec-eda6f630e7fd.jpg)

**Comment by julianpoemp** [comment]
1.10.0 crashes the same way 1.9.1 did. Huawei Mate Pro 10.

**Comment by se1exin** [comment]
I can also confirm @tasos-ale 's error on Android 9 on version 1.10.0.

@perry-mitchell looks like the javascript build step did not run during the android compile for release. I experienced this on the `rn-59` branch and had to run `npm run build:android` manually before doing a `release` build.

![Screenshot from 2019-09-15 11-55-03](https://user-images.githubusercontent.com/2385350/64915721-07b50d80-d7b1-11e9-95e6-185cb332c0a2.png)

**Comment by perry-mitchell** [comment]
Ok, thanks everyone. I’ll push a patch now to confirm that build step ran.

**Comment by perry-mitchell** [comment]
Released 1.10.1. Once again, apologies for the massive period of instability. We definitely need to slow down the release phase when pushing out new features. If 1.10.1 fails we'll roll back to 1.8.x.

**Comment by HeadFox** [comment]
Works now !! :) 
Thanks

**Comment by julianpoemp** [comment]
Works now on my Huawei Mate Pro 10. Thanks!

**Comment by perry-mitchell** [comment]
Good to hear! Thanks everyone. Enjoy the rest of your weekend.

**Comment by zappy16GB** [comment]
Good work it works on my pixel 2 xl Android 10

**Comment by ckadluba** [comment]
Thank you for the quick fix. Buttercup is really cool. I switched from KeePass.
