### ISSUE TITLE
Cannot unlock vault after updating to the latest Android app version [Decryption failed: Possible tampering]

### ISSUE THREAD

**Issue by ivanovd** [buttercup/buttercup-mobile#186]
** Describe the issue you're having **
I have just updated to the latest Android version 1.10.1 and I can't unlock my vault. I successfully unlock it in Chrome, so I know the password is correct.

_What were you doing when the issue occurred? How do we reproduce it?_
1. Add your Dropbox account
2. Authenticate
3. Select the vault
4. Try to unlock it

** What OS version are you using **
N/A

_What version of Android/iOS are you using? Eg. Android 8.0 / iOS 12.3.1_
Android 9, security patch level 2019-07-01

** What device are you using **
N/A

_What phone/tablet are you running the app on?_
Xioami Mi9T

![Screenshot_2019-09-15-12-48-07-816_com buttercup](https://user-images.githubusercontent.com/4889583/64919799-acd2e480-d7b7-11e9-8ecd-47bbec4e3e30.png)

**Comment by perry-mitchell** [comment]
Hi @ivanovd - That's strange.. if it works in the extension it should work in app. Could you try making a change and saving it in another app, then try again with the mobile app?

**Comment by ivanovd** [comment]
@perry-mitchell yeah, after I posted this I have found another thread where a similar issue has occurred and I made a change on the PC app, saved and synced and then on the mobile I was able to access the vault.

**Comment by perry-mitchell** [comment]
Hmm, seems it was some state the crypto go in to where it was failing on mobile. Ideally we'd be able to reproduce this using a test vault that someone could share with us (cc @sallar), but I'm sure that's rarely the case. 

@ivanovd Please let us know if it happens again.
