### ISSUE TITLE
Buttercup on android fails to authenticate to google drive

### ISSUE THREAD

**Issue by Gkupce** [buttercup/buttercup-mobile#188]
I just installed buttercup on my Android phone (Android version 9, security patch level "august 1, 2019") through the play store, and when trying to authenticate to google drive I get the following error:

![buttercup auth fail](https://user-images.githubusercontent.com/6500411/65007033-3af3bb80-d8db-11e9-9d8f-5bf30e28715b.png)

It opens the pop-up for account selection, but after selecting the account it shows the error.

Edit: Phone model is Motorola G7 Power

**Comment by quanhub** [comment]
Same here.

**Comment by riyadhalnur** [comment]
Could be possibly related to https://github.com/buttercup/buttercup-desktop/issues/835? @perry-mitchell  @sallar

**Comment by perry-mitchell** [comment]
@riyadhalnur It definitely could me! I'll try to get a release out asap.
