### ISSUE TITLE
Simple typo in the README PBKDF2 interations instead of iterations

### ISSUE THREAD

**Issue by timgates42** [buttercup/buttercup-mobile#193]
** Describe the issue you're having **

Simple typo in the README PBKDF2 interations instead of iterations

_What were you doing when the issue occurred? How do we reproduce it?_

Observed by reading the README

** What OS version are you using **

_What version of Android/iOS are you using? Eg. Android 8.0 / iOS 12.3.1_

Any

** What device are you using **

Any

_What phone/tablet are you running the app on?_

Any

**Comment by perry-mitchell** [comment]
Thanks!
