### ISSUE TITLE
Faster search in app (one click less)

### ISSUE THREAD

**Issue by FredrikMeyer** [buttercup/buttercup-mobile#195]
It would be nice if there were a search icon, placed something like this:
![Screenshot_20191110-14565922222](https://user-images.githubusercontent.com/1738405/68545422-5e178480-03cd-11ea-9156-cbc16787aeb1.jpg)

Would make it one click faster to search for passwords.

If it sounds like a good idea, I could make a PR.

**Comment by perry-mitchell** [comment]
Sounds great actually! If it's easy enough we'd definitely appreciate the help..
