### ISSUE TITLE
Unable to open Google Drive vault after some time

### ISSUE THREAD

**Issue by feugy** [buttercup/buttercup-mobile#206]
**Describe the issue you're having**

Adding a Vault stored on drive works well:
1. in the Vaults menu, click "add"
1. select "Google Drive"
1. select "Authenticate"
1. select one of your google account registered on Android
1. grant authorization
1. click on "Connect"
1. (select folder,) select bcup file.
1. provide master password and name
1. unlock: you can access it
1. close buttercup

After some time, your Google authentication will expire (likely, a couple of hours).
1. open buttercup
1. unlock: you get the following error:
<img src="https://user-images.githubusercontent.com/186268/69898936-1a76c180-1360-11ea-949b-4dcf7164353a.jpg" width="50%"/>

Please note it is not a typo in the master password: the same happens with biometric unlock.

**What OS version are you using**

Android 9 (last security update: 1st of August 2019), Kernel: 3.18.120-perf+
Buttercup mobile version 1.11.0

**What device are you using**

Oneplus 3T

**Comment by feugy** [comment]
Is there anything I could provide to help resolving this blocker?

**Comment by Kryszak** [comment]
I encounter same problem, removing vault and adding it again works - seems like there is problem with storing/refreshing credentials for google drive?

**Comment by perry-mitchell** [comment]
The token we receive from Google expires after an hour, I believe. Every time a request is made with an expired token it should automatically refresh it. Possible there could be an issue here, though I haven't yet seen it on iOS.

**Comment by perry-mitchell** [comment]
New version of the app is soon ready - It uses different sources for storing local details. Hopefully it'll help with this issue.

**Comment by amcclinton** [comment]
The issues still exists with the updated version. Cannot unlock google drive vault after short time on Android

**Comment by NonPolynomial** [comment]
same issue here

Android 10
OnePlus 6

**Comment by feugy** [comment]
Still happening... and causing some reputation damages: https://play.google.com/store/apps/details?id=com.buttercup&hl=en&reviewId=gp%3AAOqpTOHtZzlMxChjfZ6vTLmEvwXsDlL85augkFxZDhnPsReWoai9jNO249Fc5awxcgm_H2JFqIzs5a7ZwsEl6w

**Comment by NonPolynomial** [comment]
> Still happening... and causing some reputation damages: https://play.google.com/store/apps/details?id=com.buttercup&hl=en&reviewId=gp%3AAOqpTOHtZzlMxChjfZ6vTLmEvwXsDlL85augkFxZDhnPsReWoai9jNO249Fc5awxcgm_H2JFqIzs5a7ZwsEl6w

Do we really need to give the app a negative review on Play Store first that this bug gets a higher priority?

**Comment by perry-mitchell** [comment]
I understand the frustration here.. Bugs with our datasources are resolved with a higher priority than most other issues, _when_ we can detect them. We need to be able to reproduce the issue to fix it, and so far we haven't seen this issue ourselves.

Of course reviews are the right of the user, so if you feel negatively about the product and wish to say so, then we respect your decision there - we will not however reprioritise anything under threat of such actions. We're providing this software for free under our own effort and time. We hope that the community of awesome devs we have around us help to debug such issues so they can be fixed at a faster pace.

I can assure you that once we know what causes this, we'll deal with it as quickly as possible.

**Comment by perry-mitchell** [comment]
Can everyone confirm that they have Google Play Services installed? They're **required** for this to work.

**Comment by NonPolynomial** [comment]
hey @perry-mitchell ,

my comment was not meant to be a threat, I'm sorry that it caused this impression.

> Can everyone confirm that they have Google Play Services installed? They're **required** for this to work.

Google Play Services are installed in version 19.8.31, which is probably the newest version.

**Comment by perry-mitchell** [comment]
Ok, seems that we’ve been able to reproduce on another device - we’ll try to use this to figure out what’s wrong. No ETA yet.

**Comment by perry-mitchell** [comment]
Ok, so we suspect that there's something wrong with the configuration. I also feel that this is linked to this error, which has been appearing more recently:

![image](https://user-images.githubusercontent.com/3869469/73136263-3a6eec80-4054-11ea-9b74-63479e871d41.png)

I can now no longer get past it in development on Android. 

For some reason, Google has mentioned that our consent screen needed re-verification, which is nice, seeing as we've made no changes there nor heard any requests from them to do so. I've now submitted it for verification in the hope that it'll help, but I'm not extremely confident there - we were still under quota for users so it shouldn't be failing.

As I cannot test this exact issue, I'm afraid this whole thing is on hold on my side until something starts working in the Google realm. iOS seems to have no issues, yet the Google signin breaks on a Google-backed OS... Ironic. We'd appreciate any help/advice anyone might have on this.. thanks.

**Comment by feugy** [comment]
Hello here!

Thanks a lot for this fix.
Unfortunately, I can not really test it:
When I try to import a vault from Google drive, after successful authentication and after I gave my consent, the drive explorer is empty.
I can't see folders neither files in it:
![image](https://user-images.githubusercontent.com/186268/74607180-dd0c0f80-50d6-11ea-9f06-1b330beb4b57.png)


I can create new vault thought. The "test.bcup" file you see in screenshot above was added.
But the "damien.bcup" vault I created from desktop app, and that holds all my password, is nowhere to be found.
![image](https://user-images.githubusercontent.com/186268/74607151-8dc5df00-50d6-11ea-9ec8-b9e92271dc3b.png)

**Comment by NonPolynomial** [comment]
@perry-mitchell I can confirm, the Google Drive Sync is working!

@feugy can you open the `damien.bcup` with the desktop app and browser extension?
I never saw folders, always just the butterup files.

**Comment by Kryszak** [comment]
Sadly it still doesn't work for me, after some time after adding vault it just fails to unlock. Additionally after last update when I try to authenticate to gdrive i need to grant permissions twice.

**Comment by perry-mitchell** [comment]
@NonPolynomial @feugy New version of the Google Drive client uses **reduced permission scope**, so it doesn't show any files that weren't already touched by Buttercup.

The _browser extension_ has support for 2 modes, full-access and reduced:

![image](https://user-images.githubusercontent.com/3869469/74665112-afdb6200-51a7-11ea-899f-b58d6e2a47bd.png)

But the mobile doesn't just yet. We'll most likely release support for this option soon. For now, the vaults must be created by Buttercup.

**Comment by perry-mitchell** [comment]
@Kryszak Yeah, it seems like we fixed only half the issue. Unlocking _later_ still fails 😩. Still more to do..

**Comment by perry-mitchell** [comment]
I've created a new dev environment and have authenticated with Google.. I'll wait to see if it breaks again, perhaps I can debug it.

**Comment by perry-mitchell** [comment]
I've fixed it locally, will publish today.

**Comment by perry-mitchell** [comment]
Released under 1.14.0.

**Comment by CriPstian** [comment]
Hello, I'm encountering the issue with the Google Drive connection not able to see my vaults moved from my Dropbox account.
I can only create new vaults, but not open older ones created via desktop app.
Is anyone having the same issues? I'm on Android version `1,14.` released on 18th of February
