### ISSUE TITLE
IOS version stopped working after recent bcup updates, (IOS 10.3.3)

### ISSUE THREAD

**Issue by rugabunda** [buttercup/buttercup-mobile#211]
Buttercup starts to load and then the window disappears, its running in the background however when you try and tap the window to come forward, it minimizes to the background again... the cycle continues. The previous versions were working fine, only one of the last two recent updates appears to have caused it.

**Comment by perry-mitchell** [comment]
Interesting.. I'm not actually using iOS 10 at the moment, as it's 3 major versions old. Is there a reason you haven't upgraded?

That being said I don't think there should be much that's changed that'd affect iOS support, but we'll have to get around to checking on a v10 simulator.

**Comment by androidcn** [comment]
@perry-mitchell iOS12 same problem

**Comment by perry-mitchell** [comment]
Can someone attach a screen recording of this?

**Comment by androidcn** [comment]
https://youtu.be/-KnArheXIVk
