### ISSUE TITLE
Crash iOS12.1 Jailbreak iPhone

### ISSUE THREAD

**Issue by androidcn** [buttercup/buttercup-mobile#212]
open app crash

** What OS version are you using **
iOS12.1 Jailbreaked

** What device are you using **
xs max

**Comment by perry-mitchell** [comment]
Unfortunately there's nothing to do here. The app doesn't crash for us on that version (not-jailbroken), nor on that model phone. We wouldn't of course jailbreak a device just to test either I'm afraid. Using a jailbroken device is also questionable in terms of security, which we care about very much - I'd personally recommend not running buttercup on a jailbroken device anyhow.
