### ISSUE TITLE
Android app can't decript a vault from Dropbox

### ISSUE THREAD

**Issue by sergio-hcsoft** [buttercup/buttercup-mobile#215]
A vault created in the windows app on a dropbox account, when used from the android app it cannot be decrypted, showing a warning of possible tampered file.

Note: triple-checked password was ok, that case was ok, and no strange chars were used, just numbers and ascii letters). Of course, the file can be unlocked in the windows app nicely, 

Side notes:

1) Tried downloading the file to local storage but Buttercup can't read the file form there.

2) Tried GDrive but: (a) Windows app can't authenticate (due to new restrictions on allowed browsers in the google side), so I uploaded it manually. (b) Android app can authenticate but not connect to GDrive, it keeps "Connecting" forever.

**Comment by simonneutert** [comment]
Same on iPhone SE 2020 with newest iOS at. Cannot delete a vault, cannot unlock vault to delete.

**Comment by perry-mitchell** [comment]
Closing as this issue is ancient. Will reopen if it's reproducible on the latest versions.

Please try creating a new vault and opening that several times beforehand, however.
