### ISSUE TITLE
Touch to unlock

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#22]
Add a way, for **iOS** and **Android**, to use touch ID to lock and unlock archives. Archives can be unlocked and then added to a touch-unlocking _group_. The mechanism for initiating the unlock procedure has not been decided. The master passwords for each grouped archive should be encrypted and stored in react-native storage using some kind of ID generated securely by the touch ID authentication process.

**Comment by crankycaleb** [comment]
I haven't seen it on a roadmap so thought I'd mention it here, I presume this wouldn't be too big of a leap to include a pin to unlock as well after that groundwork is done?

**Comment by perry-mitchell** [comment]
Hi @crankycaleb 

> a pin to unlock as well 

That's a superb idea! It might be best to create it as a separate task even, as it's still some work...

**Comment by crankycaleb** [comment]
Will do, with a few more details. Thanks

**Comment by hassaanz** [comment]
Please delete this if you think it is unrelated / not required.
I found an article which explains fingerprint auth on react native. Might be a useful resource for this issue.
https://blog.theodo.fr/2018/04/add-touch-id-react-native-app/

**Comment by perry-mitchell** [comment]
@hassaanz Actually that's perfect, thank you! We'll most likely use those exact packages mentioned in that post.

**Comment by australianpokies** [comment]
Well-documented issue! Great job on this.
[![Image](https://github.com/user-attachments/assets/3e73c1b5-4016-477e-90e3-6084e649b092)](https://rickycasino3.com/)
