### ISSUE TITLE
Android - Can't use autofill

### ISSUE THREAD

**Issue by toniobido** [buttercup/buttercup-mobile#223]
When i try to use autofill nothing happened. 
I've activate autofill four Buttercup. 
I've "continue with Buttercup" button but there is no action when I hit it. 

![IMG_20200204_231810](https://user-images.githubusercontent.com/14336821/73792459-a3690980-47a4-11ea-81ca-6ebb1f571200.jpg)
  
Running on Xiaomi redmi note 8 pro with MIUI 11.0.3 (android 9)

Thanks for your great job!

**Comment by perry-mitchell** [comment]
@sallar Any chance you might be able to confirm this?

**Comment by charlyschulte** [comment]
its a problem with the MIUI software. 
just go into your settings -> apps -> buttercup  and then give buttercup access to display popup windows. this should fix the problem.
hope i could help you
