### ISSUE TITLE
Application crashes when removing a vault

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-mobile#225]
The Buttercup application is crashing after I try to remove a vault that is stored on Nextcloud. I have added archive using both "NEXTCLOUD" and "WEBDAV" options, and the app crashes when I try to remove vault that was added added in both ways.

Phone is Blackview BV9500 with Android 8.1.0

Partial stack trace:
![signal-attachment-2020-02-09-132852](https://user-images.githubusercontent.com/9976861/74101295-f34b2600-4b40-11ea-9f8c-cd2af235d19e.png)

**Comment by perry-mitchell** [comment]
This might be fixed by #228 - which should come out in the next release.

**Comment by fernandocerezo** [comment]
The same happens with the iOS version.
