### ISSUE TITLE
Password generator

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#23]
A password generation utility when editing entries. It should be available for both new entries and editing existing ones. It should be a separate page.

**Comment by moulip** [comment]
Hi,
 I'm upping this request !

**Comment by perry-mitchell** [comment]
Thanks @moulip. This is blocked by [this issue](https://github.com/buttercup/buttercup-ui/issues/7).

**Comment by ricain** [comment]
Hi, buttercup for mobiles (especially iOS) is awesome! 

Why is this basic feature is blocked?

**Comment by perry-mitchell** [comment]
> Why is this basic feature is blocked?

> This is blocked by [this issue](https://github.com/buttercup/buttercup-ui/issues/7).

Basically because the password generator component is not compatible with React native.
