### ISSUE TITLE
iOS 13: Can't remove vault profiles (app shuts down)

### ISSUE THREAD

**Issue by datashieldeurope** [buttercup/buttercup-mobile#231]
** Describe the issue you're having **

_When I wanted to delete my vault profiles (Google Drive and WebDav) , the application shuts down (V. 1.13)_

** What OS version are you using **

_iOS 13.4.1_

** What device are you using **

_iPhone X_

**Comment by dincsi** [comment]
Same in iPhone 6 iOS 12.4.5

**Comment by Samsonizor** [comment]
Same in iPhone 6s iOS 13.4.1

**Comment by simonneutert** [comment]
Same on iPhone SE 2020 newest iOS

**Comment by teon** [comment]
Same here iPhone X iOS 13.4

**Comment by ChIcKeN78** [comment]
Same on iPhone XS IOS 13.5

**Comment by Appli-chic** [comment]
Same on iPhone 8 Plus iOS 13.5

**Comment by houdini69** [comment]
Same here on iPhone 6 iOS 12.4.6

**Comment by perry-mitchell** [comment]
I haven't yet been able to reproduce this issue. I've just tested on my iPhone that removing works (production app).

I think adding a feature to clear state would be useful in case it's corruption that's causing this problem.

**Comment by perry-mitchell** [comment]
Added an to help with this: #240

**Comment by houdini69** [comment]
In my case [iPhone 6 iOS 12.4.6] updating iOS client to v1.15.0 solve this issue. App no longer crashes when removing a vault.

**Comment by dincsi** [comment]
confirmed. thank you.

**Comment by perry-mitchell** [comment]
This issue is very old, and the app has been rewritten, so I'll close it.

I'll gladly reopen if it persists.
