### ISSUE TITLE
Always unlocked TOTP Vault

### ISSUE THREAD

**Issue by nebula-it** [buttercup/buttercup-mobile#233]
Is it possible to have a vault that is always unlocked. The idea here is that I already have self hosted bitwarden as my password manager and looking to use Buttercup just as a TOTP vault. But opening app then selecting the Vault and unlocking it is a lot slower than what I would expect from a TOTP vault. It would be lovely to have an option to leave a vault permanently unlocked or use device credentials (e.g Biometrics) on app launch and a setting where app always launches to TOTP page.

**Comment by perry-mitchell** [comment]
Always-available TOTP codes is now available in v2.
