### ISSUE TITLE
Uninstall and reinstall from iOS does leave the vaults behind

### ISSUE THREAD

**Issue by simonneutert** [buttercup/buttercup-mobile#236]
** Describe the issue you're having **

Having a corrupt vault in the app, I could not delete it from my phone. I deleted the app from my phone via Settings -> delete app

Shutdown the iPhone, rebootet and reinstalled. The all vaults were still there :-(

** What OS version are you using **

iOS 13.4.1

** What device are you using **

iPhone SE 2020

**Comment by teon** [comment]
Same here - iPhone X.

**Comment by perry-mitchell** [comment]
I'm sorry for the inconvenience. We have plans to address the corruption issue: #240
