### ISSUE TITLE
Clear state feature

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#240]
Add a way to clear the state so that all vaults and settings can be removed.

**Comment by perry-mitchell** [comment]
This could be accessed via a simple menu button with a confirmation.

**Comment by FredrikMeyer** [comment]
Hi! I saw this was marked as "Available". Is it ok if I submit a PR?

I took a quick look at the code, and I think I have something that works.

Screenshots below.

<img width="478" alt="Skjermbilde 2023-02-11 kl  22 08 09" src="https://user-images.githubusercontent.com/1738405/218281476-e892dc1e-572c-4e41-9f98-016f1097942d.png">
<img width="494" alt="Skjermbilde 2023-02-11 kl  22 08 16" src="https://user-images.githubusercontent.com/1738405/218281475-6afba391-1374-47a6-90a6-669844587768.png">
<img width="485" alt="Skjermbilde 2023-02-11 kl  22 08 29" src="https://user-images.githubusercontent.com/1738405/218281471-18021e0a-8cdd-47d1-ae51-2ea8c74ef61b.png">

**Comment by perry-mitchell** [comment]
That'd be great thanks!

**Comment by perry-mitchell** [comment]
Fixed in #332.
