### ISSUE TITLE
F-Droid release

### ISSUE THREAD

**Issue by avronr** [buttercup/buttercup-mobile#241]
Hey,

I think a lot of Android users who are concerned about privacy and Google spying on them including myself would appreciate a F-Droid (https://f-droid.org/) release.
There aren't many quality password manager apps in F-Droid so I believe you guys can attract a lot of new users there.

**Comment by perry-mitchell** [comment]
Closing as it's a dupe: https://github.com/buttercup/buttercup-mobile/issues/75#issuecomment-663826695
