### ISSUE TITLE
Groups/folders are displayed flat

### ISSUE THREAD

**Issue by eandersons** [buttercup/buttercup-mobile#242]
**Describe the issue you're having**

All groups/folders and their subgroups/subfolders are displayed flat in Buttercup application on Android, that is, they are not hierarchical, therefore it may be hard to understand to what they and entries in these subgroups/subfolders refer to if they are not named explicitly.
For instance, I have a group *Nextcloud* > *Nextcloud (Instance name)* > *App passwords*, and I have many subfolders in other groups named "App passwords" (in screenshot "Lietotņu paroles").

![Screenshot_20200709-112354 1](https://user-images.githubusercontent.com/9976861/87016119-f7a26a80-c1d6-11ea-8120-d584856ccee6.png)

**What OS version are you using**

Android 8.1

**What device are you using**

Blackview BV9500

**Comment by perry-mitchell** [comment]
It's a fault with how the vault contents are processed, and nothing to do with the source. We'll try to get this patched asap.

**Comment by powerflo** [comment]
> It's a fault with how the vault contents are processed, and nothing to do with the source. We'll try to get this patched asap.

Are you already working on it or can I provide a pull request to fix it?

**Comment by perry-mitchell** [comment]
@powerflo We'd absolutely accept a PR for a fix! :)

**Comment by perry-mitchell** [comment]
Fixed in #242
