### ISSUE TITLE
Cannot unlock vault on Android

### ISSUE THREAD

**Issue by mathiasmah** [buttercup/buttercup-mobile#246]
** Describe the issue you're having **
Since a while I cannot unlock the password vault on my android phone. 
When I attempt to unlock the vault, the loading spinner just shows forever and I have to restart the app to leave this state.
In any case it almost never succeeds to unlock the vault.

The only times I could successfully unlock it, was immediately after added the vault on the phone and only by password, never by touch ID. 

** What OS version are you using **
Andorid 10 

** What device are you using **
Huawei P20

**Comment by perry-mitchell** [comment]
How big is your vault file? What service are you hosting it on?

**Comment by mathiasmah** [comment]
The file is 16 MB and I am hosting it on Dropbox.

**Comment by Aramatis** [comment]
I've having the same issue with my Huawei Mate 20 lite running Android 10 and a vault in dropbox.
I think it has to be a problem with Android 10 or EMUI 10, since the same vault works with no problem on the Huawei P20 lite running Android 9.1 I had before.

**Comment by julianpoemp** [comment]
@mathiasmah @Aramatis does the issue exist with the latest version of Buttercup mobile (2.1.0) ?

**Comment by Aramatis** [comment]
@julianpoemp since commenting on this I had to change my phone since my Huawei Mate 20 lite's battery died and corroded other parts of the phone. At least on my current phone (Motorola One Macro), I've never had this issue again

**Comment by JustPotaro** [comment]
It is happening on my Smasung S10 5G too, and I am on the latest version of the app. My file size if 114 KB and on Dropbox.

**Comment by perry-mitchell** [comment]
Would really appreciate someone trying to debug this further on their device, or send us some crash logs if it does indeed crash eventually. Otherwise there's not much to do here I'm afraid.

**Comment by perry-mitchell** [comment]
As there's no way to debug this, and no example vaults, I'm going to close this. I'll reopen if there's some actionable information. Device types that this occurs on cannot be classed as such.
