### ISSUE TITLE
Groups inside Groups are not shown on Android

### ISSUE THREAD

**Issue by GertVanKruiningen** [buttercup/buttercup-mobile#251]
Buttercup on Windows and Linux allows you to have Groups inside Groups, like creating a hierarchical structure.
This structure is not visible in Android.
BUT when creating a Group inside a Group in Android, which doesn't show properly inside Android, is correct when opening the vault in Windows and Linux.

So clearly the Android app, knows about adding Groups inside Groups, but is not showing them in a hierarchical manner.

Using Android 9.0 on a One Plus 5

**Comment by perry-mitchell** [comment]
Hi! Which version of the app are you using? This was solved with #242

**Comment by perry-mitchell** [comment]
Closing as I believe this was fixed. I'll absolutely reopen if the issue persists.
