### ISSUE TITLE
Failing to create new vault in Google Drive

### ISSUE THREAD

**Issue by catcake** [buttercup/buttercup-mobile#255]
### ** Describe the issue you're having **
I'm a first-time user and upon trying add a new fault from Google Drive, where I successfully authenticate and can connect, but on adding a new vault, after getting through the 3 pop-ups for filename, vault password, and name, it errors with "failed adding vault - Failed unlocking source: Failed at saving Google Drive Vault: Request failed: 404 undefined: Not Found"

No vault appears in Google Drive, but one with the proper (as-entered) information does appear on the Vaults tab. Attempting to unlock the vault results in a similar error "Error: Failed unlocking vault - Failed unlocking source: Failed fetching Google Drive vault: Request failed: Request failed: 404 undefined: Not found" (yes the 2 "Request failed"s).

This sounds very similar to #253.

### ** What OS version are you using **
Android 11, 8.1.0 

### ** What device are you using **
 Pixel 4a, nexus 6p

**Comment by catcake** [comment]
I've managed to work around this by creating a vault through the desktop app, then adding that vault to the app.

**Comment by lil5** [comment]
I have the same issue on iOS

**Comment by perry-mitchell** [comment]
Is this still occurring on the latest version?

**Comment by catcake** [comment]
I have not had it reoccur. Thanks!
