### ISSUE TITLE
App crashes when trying to open vault

### ISSUE THREAD

**Issue by michacassola** [buttercup/buttercup-mobile#258]
** Describe the issue you're having **

Athenticate and add Vault from Dropbox on iPadOS and try to open or unlock it afterwards makes the app crash. App is not usable.
Reopening the app and opening the vault entering the password does not successfully load it but asks me about offline usage, which then also does not work.

** What OS version are you using **

Latest iPadOS.

** What device are you using **

iPad Pro 11 inch

**Comment by perry-mitchell** [comment]
App has been completely rewritten, so I'm going to close this issue.

Will gladly reopen if it still somehow persists.
