### ISSUE TITLE
App also crashes on Android

### ISSUE THREAD

**Issue by michacassola** [buttercup/buttercup-mobile#259]
** Describe the issue you're having **

Same as on iPadOS:
Athenticate and add Vault from Dropbox on iPadOS and try to open or unlock it afterwards makes the app crash. App is not usable.
Reopening the app and opening the vault entering the password does not successfully load it but asks me about offline usage, which then also does not work.

** What OS version are you using **

Android 8.1.0

** What device are you using **

Lenovo TB-8704F

**Comment by julianpoemp** [comment]
@michacassola does the issue still exist with the latest version of Buttercup mobile (2.1.0)?

**Comment by perry-mitchell** [comment]
Closing for now.
