### ISSUE TITLE
Unlock My buttercup archive failed: UUID generation failure 20.02.2021 ADM00103

### ISSUE THREAD

**Issue by ADM001033** [buttercup/buttercup-mobile#260]
** Describe the issue you're having **

Athenticate and add Vault from Dropbox on Android 10 and try to open or unlock it afterwards makes the app crash. App is not usable.
Reopening the app and opening the vault entering the password does not successfully load it but asks me about offline usage, which then also does not work.

** What OS version are you using **

Android 10

** What device are you using **

Redmi 7A, Samsung Galaxy A7 2018

**Comment by MitchellJo** [comment]
**Try to turn off the DOH.**

This issue should be related to DOH.
I turned off DOH and it worked.

**Comment by josmith2308** [comment]
What is DOT ?

**Comment by MitchellJo** [comment]
> 
> 
> **Try to turn off the DOT.**
> 
> This issue should be related to DOT.
> I turned off DOT and it worked.

It seems not be related to DNS_OVER_TLS.
But related to "ipv4.icanhazip.com".
If "ipv4.icanhazip.com" started timing out, the app will ask to offline usage.

**Comment by perry-mitchell** [comment]
Yeah right now UUIDs are generated asynchronously on the app, as required by RN's crypto (in this build). The core expects them synchronously though, so we pre-load a bunch of them. It's a terrible solution, but we couldn't come up with a feasible alternative back then. It will  be updated in the new mobile version.

**Comment by julianpoemp** [comment]
@ADM001033 does the issue still exist with the latest version of Buttercup mobile (2.1.0)?

**Comment by perry-mitchell** [comment]
The UUID generation restriction is gone in v2, so I'll close this for now.
