### ISSUE TITLE
Repeatedly getting Offline Content popup when online

### ISSUE THREAD

**Issue by colinrobertbrooks** [buttercup/buttercup-mobile#261]
_Describe the issue you're having_

![image](https://user-images.githubusercontent.com/9815009/108611975-1e05c680-73b2-11eb-982b-4d939c32ee2d.png)

As of this evening, I'm getting the Offline Content popup when I'm online. If I delete the vault and add it again, then everything's fine until I close and reopen it once; from there on I get the Offline Content popup everytime. I tried toggling cell & WiFi, restarting the phone and uninstalling & reinstalling the app, but the result is always the same.

I'm not having any issues on desktop.

_What were you doing when the issue occurred? How do we reproduce it?_

Trying to open the mobile app.

_What version of Android/iOS are you using? Eg. Android 8.0 / iOS 12.3.1_

iOS 14.4

_What phone/tablet are you running the app on?_

iPhone 12 Mini

**Comment by ADM001033** [comment]
The same problem on android, I wrote here: https://github.com/buttercup/buttercup-mobile/issues/260

**Comment by colinrobertbrooks** [comment]
This has become intermitent for me; when it happens, toggling WiFi routinely fixes it.

**Comment by colinrobertbrooks** [comment]
No longer happening.
