### ISSUE TITLE
Auto fill doesn't work in duckduckgo on Android

### ISSUE THREAD

**Issue by Eskotus** [buttercup/buttercup-mobile#264]
In duckduckgo on Android the auto fill almost never works. 

Only site where it has come up is actually github and even there it only fills the username. 

Duckduckgo version: 5.80.0
Android 11.0.0.138
Huawei P30 (VOG-L29)

**Comment by perry-mitchell** [comment]
This is up to the website, as Apple reports the fields to our app - we don't do detection, but merely provide the username/password to Apple's autofill.
