### ISSUE TITLE
Android loading a local vault file 

### ISSUE THREAD

**Issue by powerhousepro69** [buttercup/buttercup-mobile#265]
Is there anyway at all to load a local vault file with your android app?

**Comment by perry-mitchell** [comment]
Not yet, but when 2.x comes for android in the coming week or two, this will be available. It's already implemented on iOS.

**Comment by linhandev** [comment]
Any update on this? Don't really want to route my passwd through cloud services.

**Comment by ldexterldesign** [comment]
> It's already implemented on iOS

Unless I've misunderstood loading a local vault doesn't seem to be possible in latest iOS 😕

Appreciate clarification either here or [there]

Yours hopefully

[there]: https://github.com/buttercup/buttercup-mobile/issues/329
