### ISSUE TITLE
Finger print unlock for mobile 

### ISSUE THREAD

**Issue by kri8or** [buttercup/buttercup-mobile#267]
I really like buttercup, but unfortunately in the mobile it’s quite unusable if we can’t unlock it using fingerprint. 
my password is to complicated to be typing it every time i need to login.

sorry if this does not belong in this forum.

**Comment by julianpoemp** [comment]
Buttercup supports finger print unlock, called "touch unlock"

**Comment by kri8or** [comment]
> touch unlock

Thank you!
