### ISSUE TITLE
[Android] app can't load vault via mobile internet

### ISSUE THREAD

**Issue by julianpoemp** [buttercup/buttercup-mobile#268]
I'm currently facing an issue that I can't load my vault while I'm using mobile internet. If I connect my smartphone to a WLAN  it works.

What I do:

1. Disable WLAN, open Buttercup, mobile internet is active.
2. Select my vault und do touch unlock.
3. After a short time the dialogue appears saying I were currently offline.

### System Information
- Buttercup 1.16.0
- Android 11
- Device: Samsung Galaxy S21+ 5G
- Vault retrieved from webDAV connection (owncloud)

**Comment by perry-mitchell** [comment]
@julianpoemp I apologise for such a long wait on this issue. I've not been able to provide adequate support for all of Buttercup's GH projects and the mobile app has certainly been neglected the most.

Are you still having this issue? My guess would be DNS - Something visible while on WLAN but not publicly. Are you certain the domain you used to reach the file works externally in the exact same manner?

**Comment by julianpoemp** [comment]
@perry-mitchell I just tried it again and it worked. I don't know why because I didn't change anything. Thank you for response!
