### ISSUE TITLE
When unlocking a online vault it stays offline

### ISSUE THREAD

**Issue by Ryuuzan** [buttercup/buttercup-mobile#269]
I logged to onedrive and added my vault 
Then i locked it and when i try to unlocked it i only get access to the vault in offline mode

I'm using the version 1.16.0 of buttercup
I'm using Android 9.0 on a galaxy s9

**Comment by perry-mitchell** [comment]
We don't support onedrive.. Not sure how you added it.

Offline mode is activated when the app can't reach the remote vault for some reason.
