### ISSUE TITLE
Mobile client not pushing/pulling updates to/from Google Drive vault

### ISSUE THREAD

**Issue by catcake** [buttercup/buttercup-mobile#271]
**Describe the issue you're having**
The mobile client appears to not be pushing updates to a Google Drive vault.

_What were you doing when the issue occurred? How do we reproduce it?_

I had just added an OTP property to an existing entry for a Microsoft account and shortly afterwards checked the desktop client for a OTP code, and discovering that the new OTP property was not present.

Versions/Devices
1. Desktop PC (Windows 10 Pro)
```
Edition		Windows 10 Pro
Version		20H2
OS build	19042.1237
Experience	Windows Feature Experience Pack 120.2212.3530.0

Buttercup version information:
  Desktop @ v2.10.0
  Core @ v6.0.0
  Flags: installed
```
2. Desktop PC (Arch Linux)
```
Operating System:	Arch Linux                      
Kernel:			Linux 5.14.6-arch1-1

Buttercup version information:
  Desktop @ v2.10.0
  Core @ v6.0.0
  Flags: installed
```
3. Phone (Pixel 5a)
```
Android version			11
Android security update		September 5, 2021
Google Play system update	August 1, 2021

Buttercup app version		1.16.0
```

Both the phone and desktop are connected to the internet (can reach google.com and perform arbitrary searches).

Troubleshooting steps taken so far:
(Desktop client is in Windows until stated otherwise, implied checking the desktop client for expected updates after each step)

1. Quit desktop client, then reopen vault on desktop
2. Quit desktop client, then mobile client, then reopen vault on mobile, then on desktop
3. Add new property "test" with a value of "123" in the MS account entry
4. Remove OTP on MS account, reenable it and add to the property "Microsoft [email@outlook.com] 2" on the same entry (original property name "Microsoft [email@outlook.com]")
5. Repeated step 2
6. Added "Test entry" with username "TestUser" and password "TestPassword" on mobile
7. Repeat step 2
8. Added "Test entry 2" with username "TestUser" and password "TestPassword" on desktop, check mobile client for updates
9. Quit mobile client then desktop client then reopen vault desktop then mobile, check mobile client for updates
10. (The next day) Swap to Linux, check desktop client for updates...
	
... "Test entry 2" appears but not "Test entry", the "test" property in the MS account entry, nor either OTP properties in the MS account entry.

The vault in Google Drive has been working since November, 2020. I'm unsure what has suddenly changed, as I have added OTP entries thru the mobile app before and it has worked perfectly.

Thank you,
Cat

Screenshots of the issue:
(Sorry that these are so massive)

Desktop perspective:
![Buttercup desktop screenshot of missing properties in entry](https://user-images.githubusercontent.com/15147856/134754652-39508c86-a0e7-4a97-84da-acaeccfe6a03.png)

Mobile perspective:
![Buttercup mobile screenshot of properties in entry](https://user-images.githubusercontent.com/15147856/134754716-f9cc8827-8311-49c1-be04-4bfa2ac84928.png)

**Comment by catcake** [comment]
I have added the vault to the mobile app again under the name "main2"; it is identical to the vault the desktop clients see, while the original vault ("main") is still desynced. 

I'm going to work around this issue by manually copying the updates from main to main2. Any idea how to prevent this from happening again?

Thanks,
cat

**Comment by julianpoemp** [comment]
@catcake  does the issue still exist with the latest version of Buttercup mobile (2.1.0) ?

**Comment by catcake** [comment]
I don't know. I logged into gdrive again thru the app and resynced the vault and haven't had any problems since. I still had the original vault, which still didn't work, up until the new update when all vaults cleared and had to be synced again.

**Comment by perry-mitchell** [comment]
Closing this for now. If we find a reproducible case of this I'll happily reopen.

For this to be considered as an issue to be debugged, I'd need a dummy vault that shows these signs and instructions on how to reproduce the issue.
