### ISSUE TITLE
Mobile App Suggestions

### ISSUE THREAD

**Issue by lfom** [buttercup/buttercup-mobile#273]
** Describe the issue you're having **
Some suggestions and bug reports related to the Buttercup mobile apps.

** What OS version are you using **
Android 11 (cdDRom11 GSI) / iOS 14.4.2

** What device are you using **
Huawei FIG-LX1 / iPhone 7

Again, thanks for creating and maintaining Buttercup. I have tried to use it to sync some 2FA data between desktop and mobiles but I faced some issues. I saw some recent activity in the repo, so hopefully a new version is due soon.

1. The Android app does not have the security overlay in the multitask view (iOS app seems to work fine tho)
2. No protection against screenshots/screen recording in both
3. No way to delete fields from entries in both mobile apps
4. Entry type (login, website, etc) does not reflect the entries from the desktop app
5. No entry custom icons (probably due to the issue above?)
6. Please add an option do disable copying of data to the clipboard automatically (or at least make it a long press event instead)
7. Please add an option to use the native file picker on both iOS and Android, so it is possible to use other remote services like pCloud

If you need a beta tester for the apps, please point me to the direction (I do not use Google services on Android).

Thanks again. Regards

**Comment by edblak** [comment]
eliminate the need to use cloud storage with support for local file on mobile devices

**Comment by perry-mitchell** [comment]
Please avoid making general issues like this, as it's better for everyone if each topic/issue is it's own addressable issue. 

>   The Android app does not have the security overlay in the multitask view (iOS app seems to work fine tho)

Perhaps this was a bug on the old app. It's working for me in the new version so once it's released I expect this to be fixed.

> No protection against screenshots/screen recording in both

I'm not aware of any simple way to fix this. Open for suggestions/PRs.

> No way to delete fields from entries in both mobile apps

Addressed in new version.

> Entry type (login, website, etc) does not reflect the entries from the desktop app

Addressed in new version.

> No entry custom icons (probably due to the issue above?)

Domain-specific icons now work in the new version.

> Please add an option do disable copying of data to the clipboard automatically (or at least make it a long press event instead)

I'd consider this in a new issue/PR.

> Please add an option to use the native file picker on both iOS and Android, so it is possible to use other remote services like pCloud

This would only be relevant for the local file vaults.. not cloud based options. I'd also consider a PR for this, but I won't be adding it (at least for now) myself.

**Comment by lfom** [comment]
Yeah, I agree. But I like to first get some feed back from developers, then split the issues that would have any result, if any.

1. Good to know. I saw a new iOS version was released, I will surely test the new Android version when it is enabled

2. On Android, you add FLAG_SECURE to the activity:
https://www.geeksforgeeks.org/how-to-prevent-screenshot-or-screen-recorder-in-android/
And there is something similar to iOS:
https://betterprogramming.pub/how-to-prevent-screen-capture-at-ios-14-1f01173c31c0

Should I open a new issue for it?

3. - 5. Great, thanks!

6. Good, I will open a new issue for it.

7. Actually, it is related. As I said in OP, in both Android and iOS, when you install apps like pCloud you can browse its files using the system file picker (it does not open the internal memory, it opens a different interface that lets you browse connected services too). So it would work for both setting a local vault (useful if the user has only one device) and also allow other cloud storage without the need of any extra code in the mobile app itself (just the generic file picker). I think this is the related documentation on Android:
https://developer.android.com/guide/topics/providers/document-provider
