### ISSUE TITLE
Application not available in Apple app store

### ISSUE THREAD

**Issue by Fridus** [buttercup/buttercup-mobile#274]
Hi,

Could you deploy your application in the store available in Belgium ?

Thx

**Comment by Bloepcode** [comment]
I also really want to try ButterCap, but it isn't available in the Netherlands too, I have no experience with the App Store and publishing apps on there. So I don't know how hard it is, but if it is possible it would be nice if you do it!

Thanks.

**Comment by AngelaCPulido** [comment]
Hi,
I couldn't download the app in Colombia either, I changed the region of my iPhone to USA and it won't let me download it either. Could you please update the app so that it is available in Colombia?

Thank you very much,
Kindly Regards from Colombia

**Comment by Dallas62** [comment]
Hi same issue in France.

**Comment by perry-mitchell** [comment]
Hi everyone - account had lapsed. Should be back up now.

Apologies for the inconvenice.

**Comment by Dallas62** [comment]
It's ok for me
Thanks!
