### ISSUE TITLE
Error adding vault from Dropbox

### ISSUE THREAD

**Issue by emilianoLeite** [buttercup/buttercup-mobile#276]
I recently uninstalled and re-installed Buttercup on my Android and can't add my vault from Dropbox.

When trying to login onto Dropbox with my Google credentials, I receive the following error:

![WhatsApp Image 2021-12-13 at 09 46 20](https://user-images.githubusercontent.com/7259090/145815313-29c996a3-399c-45ff-a5d4-37855b454920.jpeg)

**Comment by perry-mitchell** [comment]
Should be fixed in the new release.
