### ISSUE TITLE
Error Unlocking Vault

### ISSUE THREAD

**Issue by dkt01** [buttercup/buttercup-mobile#278]
I have a vault in Dropbox that I had been using with Firefox, Mac desktop, Linux desktop, and iOS.  After the 2.0 iOS app update, the vault was removed from the app.  I added it again, but I can't unlock the vault.  Every time I enter the password I get a decryption failed error.

**Comment by escael** [comment]
I have a similar error, updating the application. I add the Vault, enter the password but it don´t log in.

**Comment by perry-mitchell** [comment]
I've found the issue, pushing a release shortly. Sorry for the inconvenience.

**Comment by perry-mitchell** [comment]
The derivation rounds were not being picked up correctly. Newly created vaults would work, but older ones not. This will be fixed in 2.0.1.

**Comment by dkt01** [comment]
Working again in 2.0.1.  Thanks for the quick response!
