### ISSUE TITLE
[iOS] Autofill not working after upgrading to version 2.0.0

### ISSUE THREAD

**Issue by casasfernando** [buttercup/buttercup-mobile#279]
Hi,

Thanks a lot for developing this great app. I'm using it on my Linux desktops, browsers and mobile, it's really awesome.
Unfortunately after upgrading yesterday to version 2.0.0 on my iOS devices (iPhone and iPad) I discover that when trying to use Buttercup for autofill, it's not working anymore.
iOS presents the option to choose the app when trying to use autofill (keychain or Buttercup) but when I select Buttercup, the screen dims for a second and nothing happens.
As a workaround I need to manually open Buttercup, search for the credentials and then use copy and paste.

Steps to reproduce:

1. Open Firefox
2. Go to github.com and select sign in
3. Select the user field in the form and iOS will present the option to choose from Passwords
4. Tap on Passwords
5. From the application list select Buttercup

Expected result: Buttercup is launched and the user get to choose the vault to unlock it. The username and password is automatically filled-in in the login form.
Current result: screen dims for a second and nothing happens

Autofill was working fine before the upgrade.
I tried to disable and re-enable autofill for Buttercup from iOS settings but it didn't help.

I'm not sure what other information to provide so please find below a couple of screenshots that I thought may help.

iOS/iPad OS version: 15.2
Buttercup version: 2.0.0
Buttercup vault storage: webdav

Let me know if I should provide any other information.
Thanks.

<img width="414" alt="2021-12-26 10-04-35-0" src="https://user-images.githubusercontent.com/15861819/147403836-84465762-9ed8-4a49-8c19-b6e0249d96cd.png">
<img width="414" alt="2021-12-26 10-06-16-0" src="https://user-images.githubusercontent.com/15861819/147403841-5261860d-40b1-48ce-bc3f-3a5491ddf5b7.png">
<img width="414" alt="2021-12-26 10-07-33-0" src="https://user-images.githubusercontent.com/15861819/147403845-39b7faf9-713d-46ad-9810-05dd68887960.png">

**Comment by perry-mitchell** [comment]
Yeah I can reproduce this too. Thanks for the report.

I’ll be sure to look at it today..
