### ISSUE TITLE
App crashes when swipe-navigating back

### ISSUE THREAD

**Issue by escael** [buttercup/buttercup-mobile#280]
When returning with the touch closes the application.
APP version: 2.0.1
Iphone 11
IOS 15.1

**Comment by perry-mitchell** [comment]
I’m not sure what you mean. Can you describe the issue in more detail? Share a screen recording?

**Comment by escael** [comment]
Let me see how to explain it. If I navigate back with the up arrow, no problem. If I navigate backwards by dragging with the "Touch" the application closes.

No problem:
![IMG_5050](https://user-images.githubusercontent.com/1749234/147408628-9df4af88-1d4c-4236-9cb1-6e35ec746dcf.jpg)

Error:
![IMG_5051](https://user-images.githubusercontent.com/1749234/147408638-8ce400a2-8d20-4023-8727-4c9d7f3457aa.jpg)

**Comment by perry-mitchell** [comment]
@escael Indeed, I was able to reproduce. Thanks for the report!
