### ISSUE TITLE
[iOS] Wrong Buttercup version showed in About screen

### ISSUE THREAD

**Issue by casasfernando** [buttercup/buttercup-mobile#282]
This is a minor issue, but it may create confusion for developers and users alike if they need to check their current Buttercup version while reporting a bug or asking for a new feature.
After upgrading Buttercup to version 2.0.1 in the About screen the version displayed is still 2.0.0.

![image](https://user-images.githubusercontent.com/15861819/147410401-90ae525a-9826-45d1-9839-c673da20f6b3.png)

iOS version: 15.2
Buttercup version 2.0.1

Thanks.

**Comment by perry-mitchell** [comment]
Thanks, this will be fixed in the next release :)
