### ISSUE TITLE
[iOS] Autofill not working - Do not use the URL parameter

### ISSUE THREAD

**Issue by warnerbryce** [buttercup/buttercup-mobile#287]
Hello, 
This issue is kind of related to this one https://github.com/buttercup/buttercup-mobile/issues/279

Now with the latest version of iOS Buttercup, i can now start autofill but with the old version, 
the autofill process will look at the URL i'm in and then who related password. 

With this version i have a list of password that i have to pick, the URL i'm in isn't in the equation. 
There isn't at least a Search tool box. 

Thank you for correcting this. 

This new version is way more quick than the old one and after this issue fixed i can install this Password Manager for my familly.

**Comment by wdavidw** [comment]
I second @warnerbryce, I have been waiting for this version and its speed enhancement since 2-3 years to finally been able to recommend Buttercup to my surrounding. However, after beeing redirected from an app to Buttercup, searching for the correct password from the provided list is not possible, to many choices in the list and it is impossible to filter, search or navigate through the groups.

**Comment by warnerbryce** [comment]
@perry-mitchell Hello some updates on this Issue since version 2.1.0

Now the Autofill feature works great under Safari.
But i use also Firefox and on firefox no improvement. 
Before v2 the list of available password for this URL was treated by Buttercup himself not from the iOS.
There is some screenshots. 
![22-01-11 12-21-55 9498](https://user-images.githubusercontent.com/11445205/148934954-ca07da71-0169-4cbb-98e2-154d2ca53890.png)
![22-01-11 12-22-00 9500](https://user-images.githubusercontent.com/11445205/148934961-0169928d-fc1a-44b6-b170-aacc51c2cc1f.png)

**Comment by warnerbryce** [comment]
Yeah thank you so much. 
this issue is resolved in the 2.2.0 version !

i can use Firefox iOS more smoothly thanks 🙏

**Comment by wdavidw** [comment]
Wonderful!!
