### ISSUE TITLE
[Android] WebDav Syncing not working since 2.1.0 

### ISSUE THREAD

**Issue by MYDIH** [buttercup/buttercup-mobile#294]
Hi,

It seems that the webDav archives aren't synchronised anymore and that the changes made on this app aren't propagated to the archive in the webDav endpoints.

Is that the normal behaviour ?

 Thanks in advance

**Comment by mgma** [comment]
I have the same issue with v2.1.0

**Comment by casasfernando** [comment]
Can you confirm if this happening on Buttercup for iOS or Android?

I'm using Buttercup 2.1.0 daily on iOS with webdav vaults and I'm not having any issues.

**Comment by mgma** [comment]
it happens on Buttercup for Android

**Comment by casasfernando** [comment]
@MYDIH maybe you can change the issue title and add [Android] in the beginning so it's quickly visible which platform is affected from the issue list?

**Comment by MYDIH** [comment]
Done. I'm on Android too

**Comment by perry-mitchell** [comment]
We found a bug that fixed #229 - I'm wondering if it could be causing this issue as well. Please update to 2.3.0 when it's out and let us know if it's still occurring.

**Comment by mgma** [comment]
I checked the issue with 2.3.0, syncing works now.

**Comment by perry-mitchell** [comment]
That's great, thanks for checking.
