### ISSUE TITLE
[Android] [2.1.0] Google drive / can't see any existing folder files. 

### ISSUE THREAD

**Issue by cyrilnaimi** [buttercup/buttercup-mobile#295]
Hi, first thanks for the new mobile app it's a great update. 
Unfortunately the android version break the compatibility and currently have lost access to my vault on android and google drive.

After the update v1 to v2.1.0, the app ask me choose a vault (I have already my vault configured in v1.x). Ok I try to re give access to my vault. 
But I can't see it on the list neither any folder or document of my drive. 

I have the same trouble with the IOS app until the very last version where the "god bless it" checkbox grant all permission appears. 
If you do not check that buttercup have access to your drive but can only see the files and folder create by the version 2. 
So any previous vault / folder are not usable. 

Please add the same "Grant all permission" on android app too.  

Thanks. 

PS : I was never able to use my vaults due to this issue on the V1 for IOS app .

**Comment by perry-mitchell** [comment]
Hi @cyrilnaimi - Sorry for the inconvenience, and thanks for the kind words.

I've just now released v2.2.0 for Android, which adds the permissions checkbox back. Please upgrade when it's available :)
