### ISSUE TITLE
[iOS] Autofill not working - Error thrown while trying to unlock Buttercup vault

### ISSUE THREAD

**Issue by casasfernando** [buttercup/buttercup-mobile#298]
While trying to use Autofill, I'm getting an error when trying to unlock my vault.
I have biometric unlock enabled, but it doesn't work. Unlocking the vault using password doesn't work either.
I get the following error:

![image](https://user-images.githubusercontent.com/15861819/150692103-44057b8d-1f7f-49a7-9079-1765be93992f.png)

Steps to reproduce:

1. Open Firefox
2. Go to github.com and select sign in
3. Select the user field in the form and iOS will present the option to choose from Passwords
4. Tap on Passwords
5. From the application list select Buttercup
6. Tap on the vault to try to unlock it

Expected result: Buttercup vault is unlocked either by using biometrics or password. The username and password is automatically filled-in in the login form.
Current result: Buttercup displays the error in the screenshot above and the vault is not unlocked.

I tried to disable and re-enable autofill for Buttercup from iOS settings but it didn't help.

Unlocking the vault from Buttercup app works with biometrics and password without any issues. This problem is specific to autofill feature in iOS.

iOS version: 15.2.1
Buttercup version: 2.1.0
Buttercup vault storage: webdav

Let me know if I should provide any other information.
Thanks.

**Comment by casasfernando** [comment]
Updated to app version 2.2.0 and tested again. The issue is still present in this version.

**Comment by perry-mitchell** [comment]
Just tested those exact steps on 2.2.0 and it worked fine. I’ll try to dig into where that object.values call could be getting used. In the meantime I’d suggest trying to remove your vault and re add it.. or by simple disabling autofill and re-enabling it in the vault settings.

**Comment by casasfernando** [comment]
Thanks for looking into this but it’s working now.
Based on your suggestion I checked the settings of the vault and autofill was disabled there (strange thing is that I don’t remember disabling it).
Anyway, I enable it again and it’s working now.

Thanks again!
