### ISSUE TITLE
[iOS] Autofill not working on iPad - No vaults found

### ISSUE THREAD

**Issue by casasfernando** [buttercup/buttercup-mobile#299]
I'm not sure if Buttercup is supported on iPad but I was using it without any specific problems since a long time (except for app not using the full iPad screen, like other apps not designed for iPad screen specifically).
Unfortunately since upgrading to v2.1.0, while trying to use Autofill on my iPad, after selecting Buttercup a popup opens where I should see the available vaults and select one to unlock and access its secrets but instead I'm presented with the error below:

![image](https://user-images.githubusercontent.com/15861819/150692626-d3340eba-8a60-4d4b-a0f1-c7882777b964.png)

Steps to reproduce:

1. Open Firefox
2. Go to github.com and select sign in
3. Select the user field in the form and iOS will present the option to choose from Passwords
4. Tap on Passwords
5. From the application list select Buttercup

Expected result: Buttercup is launched and the user get to choose the vault to unlock it.
Current result: Buttercup is launched but an error is displayed saying that no vaults were found.

Accessing the vaults from Buttercup app itself works perfectly. This problem is specific to autofill feature in iOS.

iOS version: 15.2.1
Buttercup version: 2.1.0
Buttercup vault storage: webdav

Let me know if I should provide any other information.
Thanks.

**Comment by casasfernando** [comment]
Based on your suggestion in https://github.com/buttercup/buttercup-mobile/issues/298 I checked the settings of the vault and autofill was disabled there.
Anyway, I enable it again and it’s working now.

@perry-mitchell Is it possible that this setting is new or that it automatically changed during a previous upgrade? I’m 99% sure that I didn’t disable it myself. 

Thanks again!

**Comment by perry-mitchell** [comment]
There was a change in the default, yes: it started as on automatically but I reverted it to off. States were already set beforehand, and your entries were most likely already in the autofill provider.

As this is a minor glitch I don't think I'm going to try and make a patch or migration for it - re-enabling autofill will push the entries in correctly.

**Comment by perry-mitchell** [comment]
I'll close this in favour of #301, which will add a prompt to enable these settings when adding a new vault.
