### ISSUE TITLE
[iOS] Can't load vault in offline mode

### ISSUE THREAD

**Issue by David-Lor** [buttercup/buttercup-mobile#300]
It seems that in the new versions of Buttercup Mobile (>=v2.0.0?), on iOS at least, the Offline/read-only feature (#115) is no longer available, while before the update was working perfectly fine. Is this intentional - or maybe I'm missing where it can be enabled? Any plans on bringing it back?

**Comment by casasfernando** [comment]
I’m able to reproduce this issue as well in v2.2.0.
Screenshot of the error below:

![0C290179-4ADB-48A1-9EB9-A4837D4E2AAD](https://user-images.githubusercontent.com/15861819/151056255-68c52cbb-8ed6-4967-a3d6-551c092d5097.jpeg)

@David-Lor you may want to add [iOS] to the title to easily identify which platform is affected at the moment

Thanks

**Comment by perry-mitchell** [comment]
Sorry for the delay, this was dropped but the release (v2) went out without it _unintentionally_. I totally glossed over this feature.

I'm in the process of bringing it back, it should be ready in the next day or so, latest.
