### ISSUE TITLE
[Feature] Please add an option do disable copying of data to the clipboard automatically

### ISSUE THREAD

**Issue by lfom** [buttercup/buttercup-mobile#306]
Followup from #273: Please add an option do disable copying of data to the clipboard automatically (or at least make it a long press event instead).

Copying sensitive data to the device's clipboard can be a security issue, it would be great to be able to disable it or at least make it harder to do it with a long press.

**Comment by perry-mitchell** [comment]
Sorry, I don't agree with this one. I think copying on press is expected behaviour. If others bring up this issue I'll happily revisit but it hasn't been a problem thus far. I think what's necessary here is perhaps #309, so it's less of a risk over time.
