### ISSUE TITLE
[IOS] Failed unlocking source: Request failed: 0 undefined

### ISSUE THREAD

**Issue by game5413** [buttercup/buttercup-mobile#312]
Hello, i'm facing issue when try unlock my fault that stored at Dropbox. Try to remove vault and re-add the vault and still got same result. Already tried unlock my fault on Redmi Note 9 Pro and it's work properly, it seem an issue on IOS.

Device: Iphone 7 (IOS 15.4)
App Version: v2.3.0

![image](https://user-images.githubusercontent.com/37659721/162266354-271ba930-b296-42fe-a11b-9a32b6f374c4.png)

**Comment by perry-mitchell** [comment]
Tested that my existing Dropbox vault would still open: it does. Only after removing it and trying to re-add it did I notice this issue.

**Comment by perry-mitchell** [comment]
I have a solution: It seems as though the `Dropbox-API-Arg` header in our client is failing on mobile, so we'll be moving it from the headers to the URI as documented [here](https://www.dropbox.com/developers/documentation/http/documentation#cors). App store submission ETA tomorrow.

**Comment by perry-mitchell** [comment]
Releasing to the app stores now.

**Comment by perry-mitchell** [comment]
Seems that `2.4.1` fixed the issue partially, but it was still occurring after adding a vault. Releasing another bugfix to address that as well.

**Comment by perry-mitchell** [comment]
Released 2.4.2 now, up to the app stores for final release time
