### ISSUE TITLE
Edit passwords, Vault in Dropbox

### ISSUE THREAD

**Issue by MartinTwean** [buttercup/buttercup-mobile#314]
![2F006BF3-D7A6-4BF1-9ECC-C0B92864042F](https://user-images.githubusercontent.com/94994890/163325194-3e87cc4b-62e0-4d0d-9b2c-25eb271376ff.png)
It is not possible to edit or saving passwords.

**Comment by MartinTwean** [comment]
![Uploading 8C5E25AA-89CF-4084-BED1-F4C57E115F34.jpeg…]()

**Comment by MartinTwean** [comment]
![4918A042-E14C-481B-845C-7E1B92D326D0](https://user-images.githubusercontent.com/94994890/163435972-df8cf0ca-a7d1-4d12-a407-29896ce763d9.jpeg)

**Comment by thunsaker** [comment]
I am also having this issue on Android (2.4.2)
![Screenshot_20220503-222056.png](https://user-images.githubusercontent.com/137686/166627191-f23c3868-c851-4100-aba4-b19a49886184.png)

Steps taken: 
Remove vault, re-add vault. 
Clear app cache re-add vault.

Still on 2.3 on my iOS device, and all is working fine. I'm not updating that so I can still save passwords. 

I'll build from source tomorrow and see if I can't get more info to debug with.

**Comment by perry-mitchell** [comment]
Thanks for all the details here, I'll try to find the issue.

**Comment by perry-mitchell** [comment]
Tried adding `compat` support in the dropbox client [here](https://github.com/buttercup/dropbox-client/commit/60dee6653194755f34e16da2ffa402cbe832a3ef), but it didn't seem to help. Will look further into it tomorrow.

Note that the upcoming 2.5.0 and 2.5.1 mobile releases further break Dropbox, unfortunately, but hopefully I'll have 2.5.2 out tomorrow sometime to address this outage.

**Comment by perry-mitchell** [comment]
Found the issue: React Native is caching the request results for _fetching_ vaults from Dropbox.. We're getting a `304 Not Modified` response sometimes, breaking Buttercup as it's expecting body data and receiving none.

Fixing this as we speak.

**Comment by perry-mitchell** [comment]
Will be released in 2.5.2
