### ISSUE TITLE
Offline (local) archive support

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#32]
~Allow for archives to run offline if no network connection is available.~

~When saving and offline, write to disk. When a connection is detected, try saving to it (merge then save).~

~When saving offline, alert the user to the situation.~

~Allow for unlocking when offline. Always store a copy offline.~

~This may need to be done in core.~

Local archives on mobile.

**Comment by gschoenberger** [comment]
Currently I cannot select a locally synced buttercup file, is there a timeline, when this feature will be available?

**Comment by perry-mitchell** [comment]
> Currently I cannot select a locally synced buttercup file

I'm not sure I understand, but this sounds like a bug, rather than something relating to this issue. Could you please clarify?

With regards to a timeline: Nothing yet unfortunately. There's much to do and very little man hours to do it all in right now 😊

**Comment by gschoenberger** [comment]
I have a fresh install Buttercup app and I want to open a locally synced password file on my device not using any of the remote (Nextcloud, WebDAV) features. Is this possible?

**Comment by perry-mitchell** [comment]
@gschoenberger Of course! This is how I do it currently myself. I use ownCloud to sync my archive, and I just open it locally with Buttercup:

![image](https://user-images.githubusercontent.com/3869469/34878199-03f50fd2-f7b2-11e7-849b-f5201abdce07.png)

**Comment by gschoenberger** [comment]
Yes, I know how to do that with the desktop client, but does it also work with the android app?

**Comment by perry-mitchell** [comment]
Unfortunately local archive support is not available on the mobile - sorry for my confusion. It could be added as a PR of course, but we don’t yet have that on our timeline.

**Comment by C2c-Tuomas** [comment]
Hi, this issue will be very useful on mobile. 

In my case, I can't use the mobile apps when i'm out of home. For security reason, my NAS isn't open for external access.

**Comment by EnforcerZhukov** [comment]
Bump for this, I can't even connect my Nextcloud server from the Buttercup mobile app, so my only chance would be to use the offline, local file (synced by the official Nextcloud app). In the meantime I'll have to use another app.

**Comment by perry-mitchell** [comment]
Hi @EnforcerZhukov - We have offline read-only support for mobile now, so I'm wondering what would your use-case be for offline write? I mean, would you only ever use the app on mobile? I can appreciate that this feature is blocking for you, and I'm just trying to understand the need better myself.

**Comment by warnerbryce** [comment]
Hello, i would love to have Buttercup having access to local file for my iOS Phone. 

I have the lastest version and @perry-mitchell i don't find the read-only tab, only REMOTE. 
If i could have read-write on the local storage it would be great, it will open Buttercup to more cases. 

For me, i use Buttercup in pair with Nextcloud, so no problem for my iPhone and my computers.
But a lot of my friends want to use buttercup but don't want Dropbox, and don't have Nextcloud or WebDav. They use the iCloud Drive, and files are synced in the local storage of the iPhone too. 
So if Buttercup could connect to this storage, they will just have to add a local archive on iOS, navigate to the folder iCloud Drive, and open the archive.

What are the developpement of this feature ?

**Comment by perry-mitchell** [comment]
This feature isn't done yet @warnerbryce. Your request entails a couple of items though, one is this feature and others might be sync'ing with other services. iCloud would be a great addition of course.

**Comment by Thomazella** [comment]
@perry-mitchell is there a branch WIP for this? I could help land it.

**Comment by perry-mitchell** [comment]
@Thomazella No branch yet no, and you're welcome to submit a PR of course! You could simply add another datasource on the mobile platform that allows reading+writing to the local filesystem.

On that point however I'd recommend checking out [this comment on implementing an iOS helper for password entry](https://github.com/buttercup/buttercup-mobile/issues/125#issuecomment-450542460) - It discusses some great points on _where_ secure details can and should be stored. I think we'd probably want to store local files in the keychain but I'm not sure of storage limitations in terms of size.

**Comment by Thomazella** [comment]
Ok. looking into `react-native-secure-storage`. [Is this relevant?](https://github.com/oblador/react-native-keychain)

**Comment by perry-mitchell** [comment]
> Is this relevant?

I guess so, it seems to be _based upon_ it, whatever that means. Hopefully they mention storage restrictions somewhere (I don't have time to dig into it myself right now). Hopefully it's reasonable on both Android and iOS.

**Comment by franco27** [comment]
I too would like this feature and to be able to open a Buttercup archive locally from a folder on my smartphone.    Even if you can't change or add a password, it will be a good start.

**Comment by perry-mitchell** [comment]
To update what we're looking for here: Local vault files should be stored in the standard phone storage - it's essentially the same as storing the vault on your hard drive on your desktop/laptop. The vaults are encrypted in the same way so there's no need to write them to secure/sync storage - this would only cause unwanted merging issues.

Also, please keep the conversation here constructive - If you want this feature, please simply 👍 the first post or the one you agree with.

**Comment by Thomazella** [comment]
@perry-mitchell I'll have a wip pr up soon for this. Just to confirm what you said above: we don't want to use `AsyncStorageInterface` or `SecureStorageInterface`, but standard phone storage, bc archives themselves are already encrypted. So I basically need a way to allow user to select a file from the app (do we have a way to do this already?) and some UI on `RemoteConnectPage.js` to offer the new option. Sounds about right :D ?

**Comment by perry-mitchell** [comment]
@Thomazella The problem is actually quite complex, so let me try to break it down to manageable parts:

 * The storage mentioned above is actually for storing **the record** of the vault, and not the vault itself. See Buttercup core's [`ArchiveManager`](https://github.com/buttercup/buttercup-core/blob/master/source/node/archiveManagement/ArchiveManager.js#L23) constructor. This is the same storage as `AsyncStorageInterface` or `SecureStorageInterface`. What's recorded in this storage is _where_ the vault file is.
 * The vault file itself is stored on a remote medium, usually. On the desktop it's stored as a file of course, which is what we want to imitate here.
 * We don't want to store the local file record in `SecureStorageInterface`, because it will be synchronised to other devices using the keychain. No point syncing the record if other devices don't have the file, right?
 * Essentially we need to have _different_ storages per vault source and not 1 for the whole archive manager. This would mean modifications in the core first, somehow.

Once those are tackled, we could support local files on mobile quite easily. Perhaps adding a new config parameter to new ArchiveSources for what storage to use could help. We have the same issue in the browser extension with local files, so this would help with that too.

**Comment by perry-mitchell** [comment]
> PS: where can I ask random questions about the code?

We have a forum here too: https://spectrum.chat/buttercup

**Comment by Thomazella** [comment]
@perry-mitchell thanks, very helpful!

**Comment by Bloopps** [comment]
No news about the features for adding a local archive?

**Comment by weavermedia** [comment]
Any progress on using archives in iCloud on iOS?

**Comment by perry-mitchell** [comment]
This is not on our immediate roadmap - We would accept a contribution for this, however, in the form of a PR. For anyone interested in trying, all this would require is a new `Datasource` (see other examples in our [datasources repo](https://github.com/buttercup/datasources/tree/master/source)) called something like `MobileOfflineDatasource`, so it's nice and specific. It should work on iOS and Android.

Please don't enquire as to the progress - it will be recorded here if something happens.

**Comment by ArtexJay** [comment]
Hopefully this will be added soon, Buttercup mobile would be perfect for me if this was added.

**Comment by perry-mitchell** [comment]
It was already added. Our mobile app supports local datasources, and even offline mode when remote sources aren't available.
