### ISSUE TITLE
Last update not unlock

### ISSUE THREAD

**Issue by escael** [buttercup/buttercup-mobile#321]
After the last update it has stopped working. Does not unlock

iPhone 11. iOS 15.6.1

![E2691876-60A5-4E76-A8A9-9EB60C4D8140](https://user-images.githubusercontent.com/1749234/187655224-a70a2ee1-d634-4374-8d3c-af89e9a0afc8.jpeg)

**Comment by perry-mitchell** [comment]
Sorry for the inconvenience here. This has been fixed and a new version is being released to the app store as we speak. Version is 2.5.2.
