### ISSUE TITLE
Cannot add google vault

### ISSUE THREAD

**Issue by piotreknow02** [buttercup/buttercup-mobile#337]
OS: Android
URL: https://buttercup.pw/auth/google/?code={CODE_HERE}scope=email%20profile%20https://www.googleapis.com/auth/drive.file%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent
![buttercup-application-error](https://user-images.githubusercontent.com/65082017/232325795-4fa0d629-1ba3-4234-b432-71c9c53cf30a.png)

**Comment by carcam** [comment]
Inhave the same issue!! Any ideas on how to fix?

**Comment by dimforensics** [comment]
same issue on iOS.

**Comment by piotreknow02** [comment]
I check browser console with remote debugging, here's result:
<img width="637" alt="Zrzut ekranu 2023-04-22 o 13 39 33" src="https://user-images.githubusercontent.com/65082017/233782265-1603a64c-5691-4f78-8885-a4c1aff98163.png">

**Comment by tdislay** [comment]
For now, you just have to replace the `/auth/google/?` part in the url by `/?googledesktopauth&`

**Comment by perry-mitchell** [comment]
I was hoping to avoid having to update the mobile app right now as I'm trying to get the browser extension prepared for release. I'm afraid that any issues that might require updating the core Buttercup utilities will be blocked by us having to support ESM, somehow, in the mobile app (new JavaScript modules format).

I'd be very grateful if someone could look into the guts of this issue and see what's going wrong here.. if it's a mismatched URL path or something like that.

**Comment by tdislay** [comment]
The problem seems to come from the website, you can't open links with subdirectories anymore (e.g. https://buttercup.pw/privacy).

**Comment by perry-mitchell** [comment]
Apologies for the downtime - looking at this today.

**Comment by ttamminen** [comment]
Yes! Now it works correctly. Good work, @perry-mitchell!
