### ISSUE TITLE
Adding a vault from Google Drive causes an error "Application error: a client-side exception has occurred"

### ISSUE THREAD

**Issue by ttamminen** [buttercup/buttercup-mobile#338]
I just switched from OnePlus 7T to Motorola Edge 40 Pro, and naturally, the first to install was Buttercup. Unfortunately, I have a problem when adding a vault from Google Drive. I have Buttercup 2.5.3 installed, and the Android version is 13.

When I do all steps to authenticate (select Google account, review the permissions, etc.), it is time to watch the dance with Google and Buttercup. I get an error on the page that does all the redirecting. I attached a USB cable and tried to get all the necessary information.

The web page looks like this:
![image](https://user-images.githubusercontent.com/1038081/235111923-f3b05590-a264-4b7f-bfae-f09a599e8e73.png)

The requested URL in text form 
https://buttercup.pw/auth/google/?code=<redacted>&scope=email%20profile%20https://www.googleapis.com/auth/drive%20openid%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent

What should I do? Thanks!

**Comment by ttamminen** [comment]
Sorry, I am blind, this might be duplicate of https://github.com/buttercup/buttercup-mobile/issues/337

It didn't have Labels yet, so my search failed.

**Comment by perry-mitchell** [comment]
Will close in favour of #337 then.
