### ISSUE TITLE
No entries were found when using the autofill password in the iPhone

### ISSUE THREAD

**Issue by joshuadiezmo** [buttercup/buttercup-mobile#343]
No entries were found when using the autofill password in the iPhone

https://github.com/buttercup/buttercup-mobile/assets/8644115/04dc10cc-998e-4b6a-8693-55731a32ec30

**Comment by perry-mitchell** [comment]
Does it work if you search? Depending on the site, and what apple provides to the autofill system, it might not find any entries. You need a domain match for the site at least.

**Comment by perry-mitchell** [comment]
You can use any entry, you just have to search for it. The initial list is made using domain matching to the current page URL.
