### ISSUE TITLE
WebDav does not work on Android.

### ISSUE THREAD

**Issue by abersheeran** [buttercup/buttercup-mobile#346]
I have a WebDAV service that is proxied through Cloudflare. It has the correct HTTPS certificate and can be used normally in WinSCP or Buttercup-desktop. 
But in buttercup-mobile, when I try to add webdav, it tells me "WebDav Connection test failed". I checked the log of the WebDav service and did see a PROPFIND request, and it responded normally. Does anyone know how to solve or debug this? I am using the latest version on Google Play, which was updated on November 30th, 2023.

**Comment by abersheeran** [comment]
Everything works fine when I specify a blank directory in the url.

**Comment by accron-1** [comment]
I have the same issue/error ("WebDav connection test failed") with the Android app, but have not found a solution.
I know the WebDav url works as I have successfully connected with the desktop app as well as with my PC file explorer, but the Android app fails to connect for some reason.

Any suggestions would be appreciated.

v.2.6.1 (Dec 6, 2023)

**Comment by CreateWebNZ** [comment]
Same problem: Trying to connect to my nextcloud instance, Letsencrypt cert valid, connection works fine with FX file manager, but connection error on buttercup android. LineageOS 21 (android 14)
