### ISSUE TITLE
[iOS] Error with webdav

### ISSUE THREAD

**Issue by L42xyz** [buttercup/buttercup-mobile#349]
Hi, 

First of all, thanks for this really great app. I have been using Buttercup for years and try to promote it as much as possible!

I recently created a new archive but I can't add the vault on my iPhone. I am using webdav (from Infomaniak) and it works well on my desktop but it does not work on my phone. It refuses to accept the connection. I have tried on multiple iPhones and I can't make it work. I have tried with and without 2FA on webdav and neither of them work.

For information, everything was working before I changed my vault location.

Many thanks in advance

**Comment by Yuki21** [comment]
Hi, I can confirm this bug too: I have a self-hosted webdav server, with a valid let's encrypt certificate. It works with my buttercup-desktop application and with the android app, but not with the IOS app.
The app says something like "webdav connection test failed".
Accessing the webdav server from firefox on the same IOS device (using https, as in buttercup) works.

**Comment by aa15032261** [comment]
I have the same issue. Existing webdav vaults work but I cant add new ones.

**Comment by aa15032261** [comment]
With some digging, it is related to this bug:
https://github.com/perry-mitchell/webdav-client/issues/359

**Comment by EvilVir** [comment]
Try using IP address of your WebDav server rather than domain name. Helped here. In general mobile app is broken :/

**Comment by pilleeins** [comment]
Thanks for the great app. I have the same problem like Yuk21. Please fix. Thank you.

**Comment by janborg** [comment]
Same here, not able to add new vaults on new iOS devices!

**Comment by Yuki21** [comment]
The bug was fixed by issue #352 , this duplicate issue can therefore be closed now.
