### ISSUE TITLE
Buttercup won't open new vault on webDAV server

### ISSUE THREAD

**Issue by ValoXya** [buttercup/buttercup-mobile#352]
Hy there
I've got this strange error on the mobile version.
Once I want to add a new Vault file coming from webDAV server, there is a error says : **Connection test failed** 
but with the very same informations on my laptop it's working. No VPN used. That on iOS version (iOS17)
I suppose there is difference between mobile app and desktop version to handle connection ?

Thank you :)

**Comment by ChIcKeN78** [comment]
> Hy there I've got this strange error on the mobile version. Once I want to add a new Vault file coming from webDAV server, there is a error says : **Connection test failed** but with the very same informations on my laptop it's working. No VPN used. That on iOS version (iOS17) I suppose there is difference between mobile app and desktop version to handle connection ?
> 
> Thank you :)

I have the same issue

**Comment by jaymeanchante** [comment]
I have the same issue. My details:
Hardware: iPhone SE
Software iOS: 17.3.1
Buttercup: 2.6.1
WebDAV server: https://cloud.disroot.org/remote.php/webdav
Error: Connection failed - WebDAV connection test failed

I have just installed the desktop app under Windows 11 and I could access my vault without a problem.

**Comment by Omni1111** [comment]
我也有这个问题，使用的设备是iphone 15 pro，系统是17.3.1

**Comment by smxsm** [comment]
Same here ... I had to re-add a Webdav vault since the password has changed, but I cannot connect anymore with the new login data on iOS 17 - message: "Connection test failed" 😢

**Comment by smxsm** [comment]
I was running the project locally in the xcode iOS simulator today to debug the problem and this is what I saw in the xcode console when the error occured... it seems to be caused by an "404 not found" error - and the cause seems to be that the "url" parameter has the server url twice, separated by a space ("%20"):

![image](https://github.com/buttercup/buttercup-mobile/assets/1737182/a9a146f8-328a-43ff-97e9-f661bc7d02a3)

The simulator was running with iOS 17.2, so it seems to be a general problem, not an iOS 17.4 error ... could this be a bug introduced in one of the last buttercup releases?

I'll try to find the place where the url is set wrong ...

**Comment by perry-mitchell** [comment]
Interesting @smxsm ! Thanks for the research. I'll hopefully have time to address this next.. hopefully this week.

**Comment by smxsm** [comment]
Weird ... still does **not** work in my iPhone, even after updating to 17.4.1 and manually cleaning the doubled URL in the input field (but it **DOES** work in the xcode simulator after cleaning the URL, also with 17.4.) - so there must be another problem on the iPhone unfortunately 😢

**Comment by smxsm** [comment]
Ok, the solution is ... if I update your webdav-client lib to the latest 5.5.0 release everything works and I can add new Webdav vaults in the iOS simulator again ...
![image](https://github.com/buttercup/buttercup-mobile/assets/1737182/78255021-7068-40b4-b98e-8a29841a4766)

That's why it worked saturday night, too ... I tried that already, but had to reset my changes since I had broken the xcode project somehow.

So if you create a new Buttercup Mobile release with webdav-client 5.5.0 everything should be fine on iOS and Android again I guess 😃

**Comment by perry-mitchell** [comment]
Thanks @smxsm - Great find! I'll try to implement and release this asap.

I'm currently down a mac, and can't actually release right now because of that. I'm waiting on a new macbook so once that arrives I can push it out. ETA in the next couple of weeks, unfortunately.

**Comment by smxsm** [comment]
You're welcome 👍🏼 Let me know if I can help with the build ... but I guess you'll have to do it yourself because of the signing and appstore submission, right?

**Comment by perry-mitchell** [comment]
Yeah, I'm afraid so. Not a great situation but didn't expect it either.

If I ever get the time I'll set up an automated pipeline -> testflight.

**Comment by gravistech412** [comment]
I'm having the same issue on Android.
BC V 2.6.1

**Comment by julianpoemp** [comment]
same issue on Android v2.6.1

**Comment by perry-mitchell** [comment]
Sorry for the wait here. Had not intended on being so long without a machine to easily release with. If it shows no sign of showing up early this coming week I'll try to release the android side from a Linux setup, and iOS later.

**Comment by QuinsZouls** [comment]
@perry-mitchell 

Did you tried virtualized MAC OS with a Linux KVM? 

There's a lot of scripts out there for this. 

Also you can create iOS builds on a VM.

**Comment by julianpoemp** [comment]
@perry-mitchell have you received your mac os computer yet? If no, can you please build a version for android on Linux? This issue is very critical. I know you try your best.

**Comment by perry-mitchell** [comment]
I'll try to get to it this weekend, but I've just started a new job and I'm honestly pretty exhausted, so I can't guarantee anything.

**Comment by perry-mitchell** [comment]
<img width="337" alt="image" src="https://github.com/buttercup/buttercup-mobile/assets/3869469/1a8c0a51-768a-4f0f-8aa4-61abac585e29">

Got it working locally, will try releasing a fix this week

**Comment by perry-mitchell** [comment]
Released 2.6.2 on iOS/Android. Pending review.

**Comment by ValoXya** [comment]
Thank you so much 🥇

**Comment by julianpoemp** [comment]
@perry-mitchell the update was released on AppStore, but not on Google PlayStore. Does it take longer to be reviewed?

**Comment by smxsm** [comment]
Thank you, everything is working again on iOS 👍🏼

**Comment by perry-mitchell** [comment]
@julianpoemp It was released to both at the same time. I release to iOS first, but Android was only an hour behind. It's entirely up to them after I release, and review times are extremely volatile. 

There were new agreements I had to accept on the play store so they might have caused the review to take longer.

**Comment by julianpoemp** [comment]
WebDAV with Buttercup v2.27 on Android works. Thank you @perry-mitchell ! 🎉
