### ISSUE TITLE
Can't activate auto-fill on Android

### ISSUE THREAD

**Issue by skullysmods** [buttercup/buttercup-mobile#356]
Hello,
I can't activate auto-fill on my Android phone.
I have selected Buttercup as the autofill application in my phone's settings.

Error: "Permissions not granted".

Phone: Redmi Note 13
Android version: Android 13
Buttercup version: V.2.6.1

![Screenshot_2024-04-10-13-45-41-553_com.buttercup.jpg](https://github.com/buttercup/buttercup-mobile/assets/117316808/5426800b-edcc-4f2c-a6ba-aff5d60b391b)

![Screenshot_2024-04-10-13-55-12-490_com.android.settings.jpg](https://github.com/buttercup/buttercup-mobile/assets/117316808/0b7501b1-7b8a-4ff7-9dc0-340a91c3fb4d)

**Comment by perry-mitchell** [comment]
I only have older Android devices and can't reproduce this. Would need someone to debug this themselves in development mode.

**Comment by AlecMcCutcheon** [comment]
Same issue Pixel 6, Android 14

**Comment by lomignet** [comment]
I face the same issue. If #383 does not fix it, happy to help debugging.
