### ISSUE TITLE
Failure opening larger archives on device

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#36]
I'm not able to open my archive on my phone, it but does open in the simulator.

**Comment by perry-mitchell** [comment]
Hey @sallar - Would you be able to test on your device to see if you encounter the same issue?

**Comment by perry-mitchell** [comment]
May have just been to do with a bad build. Will keep an eye on this.

**Comment by sallar** [comment]
@perry-mitchell I guess this is resolved, havent seen any issues with it yet...

**Comment by perry-mitchell** [comment]
@sallar Nope, guess there isn't right now. 😅
