### ISSUE TITLE
Google drive 

### ISSUE THREAD

**Issue by Sony998** [buttercup/buttercup-mobile#361]
I am having problems opening my common password bault that I have had all my life, every time I try from the extension or even local from the app it simply does not recognize the .bcup file and I have not had access to my bault since the last update what can I do?

**Comment by perry-mitchell** [comment]
Sorry to hear you're having problems. It doesn't sound like this is the right repository, however. Please create a new issue for the repo+app you're having issues with, include reproduction details and errors/screenshots.
