### ISSUE TITLE
build and install manual

### ISSUE THREAD

**Issue by CircleCode** [buttercup/buttercup-mobile#5]
a small description of how to build or how to install would be welcome in the README.

**Comment by HLFH** [comment]
Is Buttercup Mobile working? Since we don't have any build instructions, I can't know.

**Comment by perry-mitchell** [comment]
@CircleCode @HLFH I've added some minor documentation to the readme. To be honest there's not really much in terms of work on the Buttercup side, but there is a lot in terms of environment setup (especially for Android). I think it should mostly work out of the box providing the desired environment is setup correctly.
