### ISSUE TITLE
[Dropbox] Archive fails to unlock & add

### ISSUE THREAD

**Issue by regoremor** [buttercup/buttercup-mobile#58]
I'm trying to add a cup file that I have in my Dropbox and after entering the password and the name is never added to the list.

**Comment by perry-mitchell** [comment]
Do you experience any error or message when trying to add? Can you confirm that the process occurs like the following:

 1. You select Dropbox
 2. You choose to authenticate
 3. You login, and it redirects back to the page
 4. Authenticate button is marked "authenticated"
 5. You Connect
 6. You locate your archive and touch it
 7. You are prompted for a password which you enter
 8. You are then prompted for an archive name

**Comment by regoremor** [comment]
The process is correct and the error window disappears very quickly and I
don't have time to take a screenshot.

Regards.

Roger

**Comment by perry-mitchell** [comment]
Ok. I'm not able to reproduce this using Dropbox with existing archives, and nor is my colleague. Could you try to open the archive using our desktop application to confirm that the password is correct and the archive is not corrupted?

If that works, perhaps you could try creating a new archive in dropbox (perhaps using the desktop application) and see if that works.

**Comment by regoremor** [comment]
Opening the archive using the desktop application works fine.

**Comment by perry-mitchell** [comment]
Could you create a new archive and see if that works using the mobile application?

**Comment by regoremor** [comment]
All my archives were created from the desktop application. This is happening to me with just a few archives. I will try to create a video.

**Comment by perry-mitchell** [comment]
> I will try to create a video.

Thank you. At least the new iOS screen capture feature will come in handy now 😅.

**Comment by regoremor** [comment]
[Video Oct 20, 3 20 03 PM.mp4.zip](https://github.com/buttercup/buttercup-mobile/files/1403058/Video.Oct.20.3.20.03.PM.mp4.zip)

**Comment by perry-mitchell** [comment]
> Video Oct 20, 3 20 03 PM.mp4.zip

Thanks @regoremor - That was a good demonstration. Seems there might be some error getting squelched. Couple of things I'd like to try, seeing as we can't yet reproduce it:

 * Uninstall and reinstall the app
 * Create a new sample archive, with a testing password, and share it with us here (so we can test it in our dropbox)

**Comment by regoremor** [comment]
With new archives does not happen. It's just happening to me with the first archives that I created in the early versions of the desktop application.

**Comment by regoremor** [comment]
When I have the option to export and import, I will create a new file.

**Comment by perry-mitchell** [comment]
Oh.. that’s weird. Maybe there’s some encoding issue?

What if you make a change to the earlier archives using the new desktop app version? This would rewrite the whole file using the latest encoding engine. You could perhaps try this with the mobile app..

**Comment by regoremor** [comment]
Yep right. I modified the contents of the archive with the problem from the desktop application and then added it to the mobile application and worked correctly.

I think all users in some way or another should know this because I have archives created from their early versions.

And I'm waiting to be able to export, import and to change the password of the files.

Thank you, Team.

**Comment by perry-mitchell** [comment]
> Yep right. I modified the contents of the archive with the problem from the desktop application and then added it to the mobile application and worked correctly.

Ok.. So there might've been an issue. In previous versions of Buttercup-core ([0.35.0 and earlier](https://github.com/buttercup/buttercup-core/blob/master/CHANGELOG.md#v0350)) there was no encoding of string values in archives. This was changed and all versions of core since are backwards compatible. It's possible that there was some kind of bug with your older archives and their content being decoded.

> I think all users in some way or another should know this because I have archives created from their early versions. 

I agree, but this is the first we've heard about this issue. If it crops up again we could consider doing a PSA, but ultimately we'd like to find an example that we could work with to address the bug itself. Let's see.

> And I'm waiting to be able to export, import and to change the password of the files.

Export will be available in the near future. Import is already available from several formats (not bcup -> bcup however..)

> Thank you, Team.

Thank you! It was great that you could work with us on this issue. We'll be sure to point others here if we hear of more problems like this one.
