### ISSUE TITLE
Intermittent crashes when using back arrow

### ISSUE THREAD

**Issue by crankycaleb** [buttercup/buttercup-mobile#64]
Sometimes app force closes upon backing out of a password. Usually when leaving app and coming back to it. So, view item, copy password, go to another app to use password, come back to buttercup app, tap back arrow to get back to list of password items, crash. Android 7.1.2. Nextcloud hosted archive. I wonder if this is just an issue with the password archive actually being locked whenever the app loses focus or something. ADB Logcat taken while issue happens is attached:
[issue.txt](https://github.com/buttercup/buttercup-mobile/files/1424705/issue.txt)

**Comment by perry-mitchell** [comment]
Hi @crankycaleb - Sorry for the inconvenience. When you say "back arrow", do you mean the hardware back arrow?

**Comment by crankycaleb** [comment]
No, the "hardware" back arrow exits the app. I'm referring to the application back arrow in the title bar. If I go right back to the app after losing focus it is fine, but anything over 30 seconds or so is when it seems to do that crash.

Great work btw, don't want to come across as "complaining". I just wanted to get a log to you. Thanks

**Comment by perry-mitchell** [comment]
Thanks for the clarification @crankycaleb.

> anything over 30 seconds or so is when it seems to do that crash

That's concerning. I wonder if there's some timer we've missed, as Android + RN famously hates background events and timers. I'm pretty sure we disabled them for Android currently (so no screen obscuring or auto-lock), but I could've missed something that's being triggered after 30 sec.

> Great work btw, don't want to come across as "complaining". I just wanted to get a log to you

Not at all! Thanks :)

**Comment by perry-mitchell** [comment]
Ok, so it seems that this is reproducible on the emulator:

```
10-31 21:05:21.419 3382-3382/com.buttercup I/System.out: Checking perms
10-31 21:05:21.522 3382-3404/com.buttercup D/EGL_emulation: eglMakeCurrent: 0xee654f00: ver 2 0 (tinfo 0xee652530)
10-31 21:05:21.546 3382-7724/com.buttercup I/ReactNativeJS: Running application "Buttercup" with appParams: {"initialProps":{},"rootTag":11}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
10-31 21:05:22.532 3382-7724/com.buttercup I/ReactNativeJS: 'Source rehydrated', { id: 'd3f98444-2721-4b3b-8bbe-692d2cb75739',
                                                              name: 'Test',
                                                              status: 'locked',
                                                              type: 'owncloud' }
10-31 21:05:26.717 3382-7724/com.buttercup E/ReactNativeJS: undefined is not an object (evaluating 'source.workspace.primary')
```

Based on the logs, it seems that the back arrow is currently killing the core application. Rehydration is taking place, so the archive is actually locked, but regular events are still trying to fire.

**Comment by crankycaleb** [comment]
Just updated to the newest version from the Play store and it's fixed now! Thanks
