### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by reuterbal** [buttercup/buttercup-mobile#69]
On the desktop client, I mostly use the search function to find credentials. I think a search function would improve the mobile app as well.

**Comment by perry-mitchell** [comment]
Good point @reuterbal!

For anyone attempting this task:

We have an `EntryFinder` class in the core library, [documented here](https://github.com/buttercup/buttercup-core#searching-for-things), which should be used for this purpose. It supports fuzzy searching, and is our preferred way of finding entries.

**Comment by mgohin** [comment]
Basic function that is reallllllly missing in the app

**Comment by willisplummer** [comment]
I've been needing a search too - I have a lot of folders and sometimes can't remember which one a login is in.. as a result I've been moving everything into a single folder so that it's at least a navigable alphabetical list

**Comment by perry-mitchell** [comment]
Released in 1.7.0

**Comment by reuterbal** [comment]
Works like a charm - thanks a ton!
