### ISSUE TITLE
React Native: security and privacy issues?

### ISSUE THREAD

**Issue by RomainQuidet** [buttercup/buttercup-mobile#72]
Hi,

I'm starting to explore your mobile app, I discovered it is based on React Native. I understand why, as you are web developers, investing in this technology helps a lot to accelerate the process.
But on another hand, introducing a Facebook library in your security app is a main concern for me: do you trust the react native library? Is there any log sent to Facebook you are not aware of? Is there a way to modify the app local js file to run something the app is not aimed to do?
I'm not confident with a security app running a 3rd party lib to interpret a js file. 

I would prefer a signed native binary app (even if jailbreak can happen etc.). In this case you master all unencrypted buffers life time, position etc. and you are more confident it is not interpreting something wrong and behaving as you coded it.

Any thoughts ?
Thanks !
Romain

**Comment by perry-mitchell** [comment]
Hi!

To be completely honest, I trust React Native as a platform. It enables many companies to get their apps off the ground easily on major platforms without the need for multiple codebases. It reduces effort and is in my eyes, an easier learning curve than compared to native languages like Objective-C or Java (which I'm both familiar with). Check out what other [companies](https://facebook.github.io/react-native/showcase.html) trust Facebook with React Native.

React Native is an open source project, in its entirety. Any of the thousands of developers/contributors can see what's going on in there, and what calls are made to what functions. If there were analytics beaming back to Facebook neither we nor anyone else would be using it.

This is the nature of the JavaScript, in terms of trust. We install familiar libraries that we trust to do a job and to not steal data. It's the same with every language or platform that employs package managers or allows for 3rd party libraries... Do you read every line of what you install? Maybe not.. but you most likely look into each project and confirm that you trust the provider enough to build with their tool.

We do the same with react native. We don't see any risk to using it, and there are a huge amount of benefits, so we chose to go that way. If they change their roadmap or want to include analytics, we'll cease to use it as a platform.

We also lock our react native version as to prevent unwanted updates. I personally check their changelogs and occasionally check out some PRs that are going through. I trust the contributors and the community to keep an eye on these projects.

I hope this addresses your questions.. React Native is right for Buttercup and doesn't compromise security. At least not more than native platforms 😊 (we would still need to install 3rd party libraries most likely 😉)

**Comment by perry-mitchell** [comment]
I'm going to close this as there's no current point at which React Native has been shown to be problematic for the Buttercup suite. If there are particular security concerns with some functionality therein, please consider opening another issue that is targeted towards that particular item.

**Comment by Developekolja** [comment]
Hello,
I'm very new to React Native and I have similar questions. I wonder if I can devolope Apps with React Native without using Facebook SDKs. I fear to face the point of having to build 50% of the code natively just to avoid the fb SDKs. Could that happen to me? Or would you say there are enough alternatives that I can trust in? After the latest issue about Facebook SDKs (https://privacyinternational.org/appdata) whitch send information to Facebook whereof many of the devolopers dind't know about I'm not sure if I should use fb SDKs.

Thanks in advance!
