### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by hassaanz** [buttercup/buttercup-mobile#74]
Hi. I cloned the repo and I am trying to build the project but the npm goes into "loadIdealTree" step and is unable to install the dependencies. If I keep it open I get the following error:

`FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

I am on Windows and would like to know if there is a specific npm version I should use to install the dependencies? I've also tried yarn but still unable to install the dependencies.

Would really love to look into the code and contribute but I need to get the project working first.

**Comment by perry-mitchell** [comment]
Hi @hassaanz - We're developing currently on Mac OS, and expect it to work there due to the ability to develop the iOS and Android platforms simultaneously. Because of that, we don't explicitly support Windows. That being said, I can't think of any reason that it should fail to install, at least.

That error seems to show that you're running out of resources. Could you please share your system specs, node version, npm version etc.

We also only support Node 8 currently.

**Comment by hassaanz** [comment]
Hi. Sorry for replying late. Here are my system details.
```
node --version
v9.2.0
npm --version
5.6.0
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 1 Stepping 1 AuthenticAMD ~3400 Mhz
BIOS Version:              American Megatrends Inc. 1.20, 3/16/2017
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     16,331 MB
Available Physical Memory: 7,732 MB
Virtual Memory: Max Size:  32,715 MB
Virtual Memory: Available: 15,378 MB
Virtual Memory: In Use:    17,337 MB
```

**Comment by hassaanz** [comment]
I just checked into verbose logs of npm and figured the problem is with the following dependency in package.json:

`"react-native-http": "tradle/react-native-http#834492d"`

**Comment by perry-mitchell** [comment]
I've finally got some time to get back on to the mobile app, and I've just seen this error for the first time. Now, after trying to install dependencies after some weeks/months, it hangs for a **long** time and then just bails and presents that error. Spends a crazy amount of time here:

![image](https://user-images.githubusercontent.com/3869469/37254848-45f5be82-254c-11e8-83cb-adbbacb18ebd.png)

**Comment by perry-mitchell** [comment]
Lol.. and then later, after removing:

![image](https://user-images.githubusercontent.com/3869469/37254932-f5d48d0a-254d-11e8-8141-eca1c2b66996.png)

This is pretty not great.

**Comment by perry-mitchell** [comment]
Ok, seems that I got it to work:

![image](https://user-images.githubusercontent.com/3869469/37255274-a118dc1c-2552-11e8-8dda-b164bbd4d36b.png)

I'll push to a branch soon. If I can confirm that everything works I'll merge it shortly. Thanks!
