### ISSUE TITLE
Unable to access Dropbox archive

### ISSUE THREAD

**Issue by johnknall** [buttercup/buttercup-mobile#82]
Since upgrading to Dropbox I’ve been unable to open my archive that is stored in Dropbox. The first time I attempt to open it it kicks me back to the login screen immediately. When I enter my password again an error message pops up on the screen but disappears in a fraction of a second. Then the application just sits there saying Unlocking but it never unlocks. This is happening on both my iPhone and iPad.

**Comment by perry-mitchell** [comment]
Hi @johnknall - I have a feeling that this is most likely caused by #78. Can you edit the archive on desktop and see if it works at all on mobile after that?

**Comment by johnknall** [comment]
I created a new entry using the desktop client and then I was able to open it on my iPhone.
