### ISSUE TITLE
Cannot connect to Nextcloud Android

### ISSUE THREAD

**Issue by all-the-good-ones-are-gone** [buttercup/buttercup-mobile#87]
Samsung Galaxy S7 
Android 7.0 March 1 security patch
buttercup 1.1.2 (2017-10-31)
Nextcloud 13.0.1

Ran buttercup AppImage on desktop, saving archive to location in Nextcloud, then installed buttercup from Play Store and tried to log in to Nextcloud, but immediately received error "**Error: Connection failed** \n Network request failed". Disabled WiFi and tried again getting "**Error: Connection failed** \n Network request failed: Timed-out after 15 seconds".
Nextcloud clients are working on desktop and mobile using same credentials.

**Comment by all-the-good-ones-are-gone** [comment]
Hello,

Yes, the URL I've entered is https://mydomain.net/ (and also without
trailing slash) which is identical to credentials entered in the appimage
and now Firefox extension. I've modified my server to use a subdomain and
not domain/nextcloud which I hope is not hardcoded in this app?

When I mentioned the credentials working on mobile I was referring to the
Nextcloud app. That works on openSUSE repo, Ubuntu PPA, and Play Store
(beta app (Galaxy S7 and Nexus 5x)) versions.
I'll try to get my wife to try buttercup on her Nexus this evening.

**Comment by perry-mitchell** [comment]
> I've modified my server to use a subdomain and
not domain/nextcloud which I hope is not hardcoded in this app

No it should definitely work on subdomains.. nothing hardcoded there.

If you could try these two items it'd definitely help narrow down the problem:

 * Try demo account at Nextcloud
 * Try using the `WebDAV` type to access Nextcloud with the full URL: `http://mydomain.net/remote.php/webdav`

Thanks!

**Comment by all-the-good-ones-are-gone** [comment]
My webdav url gave the same results as Nextcloud, but it appears generating
a demo site on nextcloud.com allowed me to log in, so there must be an
issue on my side?

**Comment by perry-mitchell** [comment]
Not necessarily.. but it's hard to discern where the problem might be.

What I usually do in these cases is attempt to help debug with the users on their actual servers, if they're amenable to such a process. Usually they create me a testing account with limited everything so I can attempt to connect from here in a development setting. I commonly use Keybase as it provides encrypted chats. 

If you'd like me to help debug directly you could contact me on keybase to provide me access, but that's of course up to you. I'm [perrymitchell](https://keybase.io/perrymitchell) on keybase.

**Comment by all-the-good-ones-are-gone** [comment]
@perry-mitchell You wouldn't happen to also be on Riot, would you?
I suppose I could look into making a keybase account.

**Comment by perry-mitchell** [comment]
Hi @all-the-good-ones-are-gone - Sorry for the delay!

I'll be checking this on the weekend at the latest, sorry.. I'm closing all issues like this due to an update to our [guidelines](https://github.com/buttercup/roadmap/blob/master/agreements/issues.md), but I'll still personally try to sort out this one issue. Let's be in touch on keybase for now!
