### ISSUE TITLE
Android device not supporting Touch Unlock

### ISSUE THREAD

**Issue by perry-mitchell** [buttercup/buttercup-mobile#89]
Seems like the touch-unlock feature doesn't work on at least some Android devices.

Seeing as we don't currently own any android devices, it'd be great if someone with a real android phone could test and confirm this.

**Comment by julianpoemp** [comment]
I still don't see any "Touch Unlock" Option on my Android phone. Where should that option be?

### System Info:
Phone: Huawei Mate Pro 10
Android: 8.0.0
Buttercup: 1.3.0

**Comment by perry-mitchell** [comment]
@julianpoemp Once you unlock an archive and are presented with the contents, open the menu in the top-right. A "Manage Archive" popup should display, and a "Toggle Touch Unlock" button should be available if the device+our-library support fingerprint recognition.

**Comment by julianpoemp** [comment]
@perry-mitchell thanks for your fast answer. "Manage Archive" seems to be just a header without any function. When I click on it, nothing happens.

<img width="200px" src="https://preview.ibb.co/jEN4kT/Screenshot_20180621_142511.jpg" />

**Comment by perry-mitchell** [comment]
Yes, "Manage Archive" is just the header. It seems as though it's detected that your device doesn't support fingerprint scanning.. Either it's a config issue with your device (I assume that it's not), or the library we're using cannot detect that your device has it.. I'll reopen, but I don't have any method of debugging this issue currently.

**Comment by julianpoemp** [comment]
@perry-mitchell the package "react-native-touch-id" you are using seems to have many issues with Andorid. Perhaps Android support is experimental? (as written in the project's description?)

**Comment by perry-mitchell** [comment]
@julianpoemp Well we had a user submit support, which worked for them. I'd really love to not have to use 2 libraries to support this, but it's looking like it might just have to be that way.

We'd need user submission for this currently as neither of us have android devices that support fingerprint recognition.

**Comment by julianpoemp** [comment]
@perry-mitchell I understand. I'm skilled in development of Angular + Typescript applications, but not in React. But if React is similar to javascript/typescript I could have a look on it after my exams. 

Alternatively you could give me apk files and I would test it.

**Comment by perry-mitchell** [comment]
I think the back and forth with using apk files would be difficult enough to warrant me buying a device myself, haha. With regards to react, you wouldn’t need to really touch it.. the logic regarding touch support doesn’t reside in any React structures really.. most difficult part would just be project structure really.

If you would have a chance to debug with your platform and device, that’d be amazing!

**Comment by julianpoemp** [comment]
@perry-mitchell Touch Unlock works now on my Huawei Mate Pro 10, Android 8 with app version 1.4.1 :smile:. Thanks! :+1:

**Comment by perry-mitchell** [comment]
Amazing, thanks @julianpoemp!

I'll close this now then.
