### ISSUE TITLE
[iPhone] App freezes when writing changes

### ISSUE THREAD

**Issue by C2c-Tuomas** [buttercup/buttercup-mobile#91]
Hey guy,

I'm testing our beautiful app. I really like it. But I've a big big case on my iPhone : I can't save anything. 

I test WebDAV and Dropbox.
Same result if I create the new file with iPhone or iMac.
I try to des/reinstall ...

>> I can't save new entry or a new group on the iPhone. He freeze on the "saving" screen.

**Comment by perry-mitchell** [comment]
Hey guy, 😂

Thanks for the kind words!

Sorry to hear about your issue. What iphone are you using, and what version of iOS? I can't imagine an issue where it wouldn't save on any platform. Are you creating a new archive or editing an old one? Perhaps you could share your exact steps here to reproduce the issue.

**Comment by C2c-Tuomas** [comment]
iPhone SE 64Go with iOS 11.3.1 (last update)

I try 4 different way to do :
1. Create archive on the iPhone through dropbox > freeze when create entry or group
2. Create archive on the iPhone through webdav > freeze when create entry or group
3. Create archive on iMac and access through dropbox > again ...
4. Create archive on iMac and access through webdav > again ...

Same if I access with password or activate Touch ID 
When I try to create group, I get an error screen with code 412.

Don't crash if I edit an entry previously created with iMac.

Hope this will help. I keep my eyes here in case of !

**Comment by perry-mitchell** [comment]
Any chance of a screen shot? Perhaps you could also share one of these test archives you’ve created that don’t work? They’re just text so you could share it here in a code block.

**Comment by C2c-Tuomas** [comment]
for sure. 

[https://s15.postimg.cc/qzzq5dzhn/IMG_2193.png](Screenshoot)

`b~>buttercup/a2K4sqtOALX7kheMABgRatnarNBhppp4zMQhaJW+h99KWrlyw3cHC7AHNmGkaUStIfpLqZvBMTEP4fKpel7wd/Ov/dPL9y/2rpiRwBSY0uebzXgKv8UI2rVgl4zX5FDYmrUg6bb2ij7Q+SQZt02H3j6MTAWURDVT27re5JZ4PYzy3yAgcbZelwgR3GJTgYjzGqFV39rds9NtkucEfW2OnOsSf+BEOv7I6xikOkzFM5iO0oXEFFM5ZcGuRNjFnXwnPBHqUAPTSNcDbtM36+yedKAhd+1dxYr5QoHz+72v0kB2bCS1bDUIIBGPq8AP7Hf4alCP84l9J2SFFJxHjF8swfkOn01a1Dy4WyaWA8kRQqExCKYVdZ7L5cRgb1rRz1g5yOFAz9j8RQKDCoNFgi6CjZ4zL9L+otBue4zPo1A6aZ4C+k2OL9yik0AZkdXvNa0ewkPS8N8ssizJzKRyYFECaAtwZAoYOi8ZsMJuKhruCEgqfPFFDtCZ4S1uAfyCqC32B0pg07/tOtyMOHNoLBGH5DFwrToguRFZHDXQNoaqY+lUNuFgVx8/xxsCLW7D0hPS839jnOKPLcvXCyHEtaxKCeyJtGumXoToU8phnHOg1v/2b7BI+eYpAPudDzZyQeNl6$e78c00b695c94c33755fe95705665234$36666332253e$155b705cd97772bc8d51199981f92275cb63af97f13489b6f27064dabafee72d$211621`

**Comment by perry-mitchell** [comment]
@C2c-Tuomas Did you happen to see any message box pop up, even very briefly, before it hangs?

**Comment by C2c-Tuomas** [comment]
One time, I saw a popup with code error 412.

**Comment by perry-mitchell** [comment]
The fact that the error msg disappears may be resolved with #61, which should help further debugging.

**Comment by C2c-Tuomas** [comment]
Sorry to heard that ;(

**Comment by perry-mitchell** [comment]
@C2c-Tuomas what was the password for the archive you shared here? I presume that it was a test archive and the password was not sensitive..

**Comment by C2c-Tuomas** [comment]
@perry-mitchell Was a test file. And I forget the password ...

I reinstall apps on iMac and iPhone. 

It's work if I use Dropbox.
Problem comes with WebDAV. I think isn't due to .bcup file's.

**Comment by perry-mitchell** [comment]
What webdav service did you use?

**Comment by C2c-Tuomas** [comment]
Synology

**Comment by claystation** [comment]
Exact same issue here. I really want to use webdav (synology) for this. Buttercup seems very promising.

Any way to avoid this? Should i create a bcup file on a computer first and then open it on my phone?

I just tried creating a group next to the default “general” group. That gave me a 412 error.

I hope there is a fix for this. Really want to use this!

Specs: Iphone XR iOS 12.1.3
Buttercup is latest from the app store.

**Comment by claystation** [comment]
Ah okay, so i tried the following. I created the bcup file through the app. Couldn't write to it.
So today i opened it up on the desktop. Wrote an entry in it and it saved perfectly.

So, when opening the archive again on iphone, it didnt show any changes. I readded the archive on the iphone, and now it works. Don't know what is causing the bug, but this is how i managed to fix it.

**Comment by x572b** [comment]
I have same/similar issue with iOS 13.5.1 attempting WebDAV on pCloud. Buttercup hangs making new vault with no error messages. I do have read/write access and WebDAV works with other apps. Buttercup seems to never make the vault. 
![49935210-DD86-4FEA-BA89-AAE4D955743C](https://user-images.githubusercontent.com/29242622/86152297-963b1700-bac5-11ea-8155-d3e8bff13d35.png)

![72551C76-EF5E-4347-B8B4-69C544BBDD89](https://user-images.githubusercontent.com/29242622/86152872-70624200-bac6-11ea-87ad-165cffcc0ad1.png)
![69339592-B9BB-4C25-B913-84F6CF5D72CB](https://user-images.githubusercontent.com/29242622/86153028-a7385800-bac6-11ea-9e97-f551914b6e41.png)

**Comment by perry-mitchell** [comment]
This is impossible to debug remotely, as webdav works normally on services that are well known providers of it (such as Yandex). It'd be fantastic if someone could debug it locally using this project in development mode, as then they'd be able to see why the request fails.

**Comment by x572b** [comment]
Thanks for the feedback. I am over my head trying to debug locally - I tried to compile and run in Xcode and npm on my Macbook last night but kept getting errors and couldn't get the project to run (real newbie). I was hoping to provide something useful but I'm afraid I didn't have much success. 

`1608	debug	12:38:07.835541-0500	Buttercup	Ping timer fired, resetting watchdog
1608	debug	12:38:12.671473-0500	Buttercup	Ping timer fired, resetting watchdog
1608	debug	12:38:13.815342-0500	Buttercup	nw_channel_purge_idle_block_invoke Purging channel packet pool after going idle
1608	default	12:38:13.957453-0500	Buttercup	tcp_input [C1.1:3] flags=[F.] seq=2867940936, ack=4252286284, win=58 state=ESTABLISHED rcv_nxt=2867940936, snd_una=4252286284
1608	default	12:38:13.957586-0500	Buttercup	nw_protocol_tcp_log_summary [C1.1:3] 
	[2699BC62-8C44-4BFB-9B57-356D30928E97 <private>:57419<-><private>:443]
	Init: 1, Conn_Time: 100.064ms, Syn's: 1, WR_T: 0/0, RD_T: 0/0, TFO: 0/0/0, ECN: 0/0/0, TS: 1
	RTT_Cache: none, rtt_upd: 9, rtt: 73.937ms, rtt_var: 29.062ms rtt_nc: 73.937ms, rtt_var_nc: 29.062ms
1608	default	12:38:13.957881-0500	Buttercup	nw_protocol_boringssl_input_finished(1700) [C1.1:2][0x1016b9a90] state: 2
1608	default	12:38:13.957932-0500	Buttercup	Connection 1: read error 0:0, eof[Y]
1608	default	12:38:13.957978-0500	Buttercup	Connection 1: read-side closed
1608	default	12:38:13.958661-0500	Buttercup	Connection 1: is being canceled
`
The above is from my console log from my iphone while trying to create a new vault via webdav on put.io. Not sure if there is anything useful there. The entire colsole log filtered for "buttercup" is attached but again might not be helpful. I apologize if I am adding "noise." 
[buttercup-iphone-console-log.txt](https://github.com/buttercup/buttercup-mobile/files/4859488/buttercup-iphone-console-log.txt)

**Comment by perry-mitchell** [comment]
V2 is out, and this issue's details are out of date. I'll close it for now. Please let me know if it still occurs.
