### ISSUE TITLE
Scroll don't work

### ISSUE THREAD

**Issue by asantisteve** [buttercup/buttercup-mobile#98]
The iOS app show the first 9 custom fields, but if you have more the scroll bar doesn't appear so you can't view all the fields.

**Comment by perry-mitchell** [comment]
Thanks for reporting @asantisteve! I'll try to get to this tomorrow.

**Comment by asantisteve** [comment]
Thanks to you! Very good work and nice project!

Albert

**Comment by perry-mitchell** [comment]
🙏

**Comment by perry-mitchell** [comment]
@asantisteve This has been fixed and will go out in the next few days, with the next release.
